### ISSUE TITLE
do not want to deleteing message from local folders when deleted from remote repository

### ISSUE THREAD

**Issue by naveen1336** [OfflineIMAP/offlineimap#211] opened 2015-06-18 12:52 UTC
is there any setting in offlineimap to restrict offlineimap to delete emails from local repository when deleted from remote repository if possible how to do that

**Comment by manuelRiel** [comment] 2015-06-25 00:51
There are two settings that may be interesting for you:

`realdelete`: Only removes message labels, but doesn't delete it. Sounds like it was made for Gmail.
`readonly`: Makes the repository read-only, thus only syncing one-way.

The first one may be your best bet, if you are looking to dump all mails in an archive, while still adding new messages.

**Comment by naveen1336** [comment] 2015-06-26 07:04
is these setting work on [local repository] section of config file

**Comment by ojdo** [comment] 2015-07-29 15:07
There is [discussion from May in the newsgroup](http://thread.gmane.org/gmane.mail.imap.offlineimap.general/7318) about a patch ([commit here](https://github.com/OfflineIMAP/offlineimap/commit/266c88f7a1b041ba169e0c0cab767bf412c23672)) that introduces a `no-delete-local` option. The patch is quite short, but some issue remain (no dashes in config options) before it can be included.

**Comment by nicolas33** [comment] 2016-04-09 20:17
Duplicate of #47.
Implemented recently. See #47 for details.

**Closed by nicolas33** 2016-04-09 20:17 UTC
Labels: feature, need contributor!

**Comment by naveen1336** [comment] 2016-07-05 21:09
thanks nicolas33 finally this feature include
