### ISSUE TITLE
SSL Certificate Verify Failed every time. 

### ISSUE THREAD

**Issue by ekiim** [OfflineIMAP/offlineimap#597] opened 2019-02-15 00:44 UTC
#### General information

I'm trying to use `offlineimap` with some of my email accounts, but I can't get it to work. 
It always fails with the SSL certificates, I tried with my personal account, and some Gmail accounts and nothing. 

I attempted to use specific files for each account, and to use the `/etc/ssl/certs/ca-certificates.crt` and when with the root one It says that there is no certificate for the domain, and when I point it directly to the certificate I generated It says that I can't validate. 

Is this something about my SSL configuration on the system, or is it something with offlineimap? 

Also It's worth mentioning that I'm using Python 3.7, and the whole process traces back to the `ssl.py l-1117` and It references the C file at line `_ssl.c:1056`, and the Python2.7.15 Yields the same output but in line (`590` of the C file) and error but like in [Issue #453](https://github.com/OfflineIMAP/offlineimap/issues/453)

Any Ideas how could I work around this? 

- system/distribution (with version):  Manjaro 18.0.2
- offlineimap version (`offlineimap -V`): offlineimap v7.2.2, imaplib2 v2.57 (bundled), Python v3.7.2, OpenSSL 1.1.1a  20 Nov 2018
- Python version: 3.7.2
- server name or domain: `mail.ekiim.me`
- CLI options: `offlineimap`

#### Configuration file offlineimaprc
```
[general]
accounts = self_ekiim.me
ui = ttyui

[Account self_ekiim.me]
localrepository = self_ekiim.me_local
remoterepository = self_ekiim.me_remote

[Repository self_ekiim.me_local]
type = Maildir
localfolders = ~/Mail/ekiim.me/self

[Repository self_ekiim.me_remote]
type = IMAP
remoteuser = self@ekiim.me
remotepass = password
remotehost = mail.ekiim.me
sslcacertfile = ~/.certs/mail.ekiim.me.pem
# sslcacertfile = /etc/ssl/certs/ca-certificates.conf
ssl_version = tls1_2
```
#### Logs, error

```
OfflineIMAP 7.2.2
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v3.7.2, OpenSSL 1.1.1a  20 Nov 2018
Account sync self_ekiim.me:
 *** Processing account self_ekiim.me
 Establishing connection to mail.ekiim.me:993 (self_ekiim.me_remote)
 ERROR: Unknown SSL protocol connecting to host 'mail.ekiim.me' for repository 'self_ekiim.me_remote'. OpenSSL responded:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
 *** Finished account 'self_ekiim.me' in 0:00
ERROR: Exceptions occurred during the run!
ERROR: Unknown SSL protocol connecting to host 'mail.ekiim.me' for repository 'self_ekiim.me_remote'. OpenSSL responded:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

Traceback:
  File "/usr/lib/python3.7/site-packages/offlineimap/accounts.py", line 283, in syncrunner
    self.__sync()
  File "/usr/lib/python3.7/site-packages/offlineimap/accounts.py", line 359, in __sync
    remoterepos.getfolders()
  File "/usr/lib/python3.7/site-packages/offlineimap/repository/IMAP.py", line 452, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/lib/python3.7/site-packages/offlineimap/imapserver.py", line 658, in acquireconnection
    exc_info()[2])
  File "/usr/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/offlineimap/imapserver.py", line 572, in acquireconnection
    af=self.af
  File "/usr/lib/python3.7/site-packages/offlineimap/imaplibutil.py", line 194, in __init__
    super(WrappedIMAP4_SSL, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/offlineimap/bundled_imaplib2.py", line 2183, in __init__
    IMAP4.__init__(self, host, port, debug, debug_file, identifier, timeout, debug_buf_lvl)
  File "/usr/lib/python3.7/site-packages/offlineimap/bundled_imaplib2.py", line 361, in __init__
    self.open(host, port)
  File "/usr/lib/python3.7/site-packages/offlineimap/imaplibutil.py", line 202, in open
    super(WrappedIMAP4_SSL, self).open(host, port)
  File "/usr/lib/python3.7/site-packages/offlineimap/bundled_imaplib2.py", line 2196, in open
    self.ssl_wrap_socket()
  File "/usr/lib/python3.7/site-packages/offlineimap/bundled_imaplib2.py", line 548, in ssl_wrap_socket
    self.sock = ssl.wrap_socket(self.sock, self.keyfile, self.certfile, ca_certs=self.ca_certs, cert_reqs=cert_reqs, ssl_version=ssl_version)
  File "/usr/lib/python3.7/ssl.py", line 1222, in wrap_socket
    suppress_ragged_eofs=suppress_ragged_eofs
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
```

**Comment by nicolas33** [comment] 2019-02-15 01:19
offlineimap won't work with python3. Does it work with python2 ?

BTW, offlineimap.py starts with `#!/usr/bin/env python2`.

**Comment by ekiim** [comment] 2019-02-15 15:30
I tried it with python2.7.15 and it manifests the same problem. But as I mentioned it gets stuck in the same python line but in a different C line.

**Comment by nicolas33** [comment] 2019-02-15 15:48
Does your own certificate (PEM) work with openssl (`openssl s_client -connect`)?

**Comment by ekiim** [comment] 2019-02-15 15:49
I ran `openssl s_client -connect mail.ekiim.me:993` and It returned a verify 0, or verify 1 at times.

**Comment by nicolas33** [comment] 2019-02-15 15:53
Add the -cert CLI option to check the PEM.

**Comment by ekiim** [comment] 2019-02-15 15:56
ok, then doing that, I directed the output to a file, save it as `pem` and then use that as `sslcacertfile`, and that should be it? or is that just to validate that SSL works? (asking because I have no way to test it rightaway)

**Comment by nicolas33** [comment] 2019-02-15 15:58
I'd like to check that the PEM is valid and working with openssl.

**Comment by ekiim** [comment] 2019-02-15 15:59
okok, I'll reply in a couple of hours, thanks.

**Comment by ekiim** [comment] 2019-02-16 05:32
ok, this is the out put of `openssl s_client -connect mail.ekiim.me:993 < /dev/null`
```
CONNECTED(00000003)
---
Certificate chain
 0 s:CN = ekiim.me
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFsTCCBJmgAwIBAgISA3/K17vv/aHRARMZEGQmapO6MA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTAxMDMwNzAzMTBaFw0x
OTA0MDMwNzAzMTBaMBMxETAPBgNVBAMTCGVraWltLm1lMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEA1tMcOM+VUb5mfT0886gYn7+L3Fp64Iyu4vaCoZMo
UZLdPkyUWQDt6lrKoESj0EYdEf0ijA4/bQeryDyXcPfFE6zU4Ud6WwAat1XwmejF
GFDJuqGIZwTWc6wy4zbgmIcy1HKX5Dwq/hYtGXNGeUOFm8uTg67lUlNyXxdtQ+xT
LB00cFI88mzNTEe6qZciu3avgmTecShfOT2aLITeR16iGzMP5TOdvbQBSK5Pm05M
x95NjkVVKkh14mKZN8Kv4wXC2+a5S0chszYhvaazCcDG30EtqCTdHj5bqs95HC4a
YVYSENhkLkjFRYZ+wovPMt0VUOMdfwXBVTg+/2SYz0fFEwIDAQABo4ICxjCCAsIw
DgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAM
BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTAiIQg94U3f7r4/rNPVtmLopJNnTAfBgNV
HSMEGDAWgBSoSmpjBH3duubRObemRWXv86jsoTBvBggrBgEFBQcBAQRjMGEwLgYI
KwYBBQUHMAGGImh0dHA6Ly9vY3NwLmludC14My5sZXRzZW5jcnlwdC5vcmcwLwYI
KwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRzZW5jcnlwdC5vcmcvMHwG
A1UdEQR1MHOCFWF1dG9kaXNjb3Zlci5la2lpbS5tZYIPY3BhbmVsLmVraWltLm1l
gghla2lpbS5tZYINbWFpbC5la2lpbS5tZYIQd2ViZGlzay5la2lpbS5tZYIQd2Vi
bWFpbC5la2lpbS5tZYIMd3d3LmVraWltLm1lMEwGA1UdIARFMEMwCAYGZ4EMAQIB
MDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2Vu
Y3J5cHQub3JnMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHcAdH7agzGtMxCRIZzO
JU9CcMK//V5CIAjGNzV55hB7zFYAAAFoErzTSQAABAMASDBGAiEA+QJyGUOErg8Z
Bue52VjdxsYziU7SpFP8BSIr01/7DfgCIQDL1YZVrnupSK+D9BM4cAnLk269qvER
Mu64eGejR7k34wB1AGPy283oO8wszwtyhCdXazOkjWF3j711pjixx2hUS9iNAAAB
aBK80bwAAAQDAEYwRAIgO3jkFXgexkNKE09ZpNqJqPLlyNiZAzwjXnw/otlq5YkC
IF5wTZ2XvkHXzI8GYwALwNCk5RvdW0MwxoaVqtVZ/bgRMA0GCSqGSIb3DQEBCwUA
A4IBAQAyRG0E5uO5NuMfmqhMFwsRhiebz26jlwtb/JOa0Bynnvk5H9Mwnjm83fis
TbMObl+Za6Q5z+JZ3XQfAH6maU6uH1cKRo7cIZ2nRNPuAyfvBycWqEB7JvGw8F2S
A9YJjhVX7TZrirqfmrbulJ+1hF78TFd9itk5R0YbeLhsGIG+oPBlmV+a3QJGcINW
S1JjUnLmyD4Omq8+xr+eICVThMHIRW0y8JQKcaNRrFP1EfzZTgDX7K2wVkhHSYik
Vj4RD/MoeobnOB3uZFCqTXnWq401Dz8RxK5zhg26b+K8umJhR5pvuQNEaQIp9RLS
gH6Dw5doL4uL+zZLOQRKyIIulxy+
-----END CERTIFICATE-----
subject=CN = ekiim.me

issuer=C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-384, 384 bits
---
SSL handshake has read 3344 bytes and written 473 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 6D9D3CAADC4EDD9AEFB5E41869D5F871A919B0ACA0481FBF6F04C35F9E805350
    Session-ID-ctx: 
    Master-Key: 3DED8FE59952E526B45711E79467C267CBDF6686AC9EC9E47830315B99C5E8B5F6A00DEFAF73A903C8DC0738D1B35299
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 97 c1 ca 9c 49 a1 8b 74-fa 50 b9 b5 a3 4c da b3   ....I..t.P...L..
    0010 - 28 06 13 38 94 72 cd 92-8c 3a cc 52 ef f0 ff 9e   (..8.r...:.R....
    0020 - 3b 6e 98 77 64 5c 72 7c-6f 0d 24 9e 5c 43 3d d4   ;n.wd\r|o.$.\C=.
    0030 - 90 71 67 b1 a6 bb 90 a9-e4 33 05 99 4c f5 d3 66   .qg......3..L..f
    0040 - 8d 3f b1 69 99 bb 8c 7e-c7 fb f6 02 f5 7e ae 90   .?.i...~.....~..
    0050 - 34 68 29 77 19 71 13 13-42 fe c6 29 72 10 da 6b   4h)w.q..B..)r..k
    0060 - 27 e8 60 57 be 47 34 ff-ee ef 63 c1 d6 d0 fd 0b   '.`W.G4...c.....
    0070 - a3 07 bf 3d ab 21 60 6d-ba 3b 5c 47 4d 07 e4 dc   ...=.!`m.;\GM...
    0080 - f9 4d 6c 5f c1 f7 93 38-53 75 07 4f d1 ba ee a3   .Ml_...8Su.O....
    0090 - 15 00 85 e9 49 09 a9 86-69 6a e3 6b d7 bd f8 68   ....I...ij.k...h
    00a0 - 02 5d 7f a4 ff ce bb 75-9d a8 9e 56 40 06 a5 04   .].....u...V@...

    Start Time: 1550295071
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

**Comment by nicolas33** [comment] 2019-02-16 21:25
This command didn't check the local PEM file. Outside a wrong PEM file I don't get what could hurt.

As a workaround you could use the cert_fingerprint check.

**Comment by ekiim** [comment] 2019-03-27 20:30
Sorry I took so long, now look I tried it now with gmail account, and I'm getting this output.
with the following config. 

```
[general]
ui = ttyui
accounts = Gmail
socktimeout = 90 
ssl = true
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
ssl_version=tls1_2

[Account Gmail]
localrepository = Gmail-Local
remoterepository = Gmail-Remote

[Repository Gmail-Local]
type = Maildir
localfolders = ~/Mail/Gmail

[Repository Gmail-Remote]
type = Gmail
remoteuser = ACCOUNT@gmail.com
remotepass = password
realdelete = no
maxconnections = 3
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
```

when `offlineimap 2>&1` 
```
OfflineIMAP 7.2.3
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.15, OpenSSL 1.1.1b  26 Feb 2019
Account sync Gmail:
 *** Processing account Gmail
 Establishing connection to imap.gmail.com:993 (Gmail-Remote)
 ERROR: Unknown SSL protocol connecting to host 'imap.gmail.com' for repository 'Gmail-Remote'. OpenSSL responded:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
 *** Finished account 'Gmail' in 0:00
ERROR: Exceptions occurred during the run!
ERROR: Unknown SSL protocol connecting to host 'imap.gmail.com' for repository 'Gmail-Remote'. OpenSSL responded:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)

Traceback:
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 283, in syncrunner
    self.__sync()
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 359, in __sync
    remoterepos.getfolders()
  File "/usr/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 452, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 658, in acquireconnection
    exc_info()[2])
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 572, in acquireconnection
    af=self.af,
  File "/usr/lib/python2.7/site-packages/offlineimap/imaplibutil.py", line 194, in __init__
    super(WrappedIMAP4_SSL, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 2183, in __init__
    IMAP4.__init__(self, host, port, debug, debug_file, identifier, timeout, debug_buf_lvl)
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 361, in __init__
    self.open(host, port)
  File "/usr/lib/python2.7/site-packages/offlineimap/imaplibutil.py", line 202, in open
    super(WrappedIMAP4_SSL, self).open(host, port)
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 2196, in open
    self.ssl_wrap_socket()
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 548, in ssl_wrap_socket
    self.sock = ssl.wrap_socket(self.sock, self.keyfile, self.certfile, ca_certs=self.ca_certs, cert_reqs=cert_reqs, ssl_version=ssl_version)
  File "/usr/lib/python2.7/ssl.py", line 949, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 617, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
```

**Comment by nicolas33** [comment] 2019-03-28 11:03
Ths ssl configuration options must stand in the remote "Repository" section.

**Comment by vorner** [comment] 2019-08-19 19:56
This is happening to me too.

I tracked it down to version of openssl ‒ it works fine with 1.1.0k, doesn't work with 1.1.1c.

**Comment by mvanbaak** [comment] 2019-09-24 10:43
Duplicate of #573 ?

**Closed** 2020-02-12 23:24 UTC
