### ISSUE TITLE
Crash on OSX Yosemite python 2.7.6 (latency)

### ISSUE THREAD

**Issue by gabrielstuff** [OfflineIMAP/offlineimap#205] opened 2015-05-21 15:27 UTC
Hi !

I'm trying to synch my email (quantity: 90k), and it keeps crashing.
Here is the log : 

```
Last 7 debug messages logged for Copy message from Remote:INBOX prior to exception:
thread: Register new thread 'Copy message from Remote:INBOX' (account 'Gabriel')
imap: Using STARTTLS connection
imap: Attempting PLAIN authentication
imap: __plainhandler: returning gabriel@soixantecircuits.frXXXXXXXXX
imap: Using STARTTLS connection
imap: Attempting PLAIN authentication
imap: __plainhandler: returning gabriel@soixantecircuits.frXXXXXXXXX
ERROR: Exceptions occurred during the run!
ERROR: command: UID => socket error: <class 'socket.error'> - [Errno 54] Connection reset by peer

Traceback:
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/folder/IMAP.py", line 660, in _fetch_from_imap
    res_type, data = imapobj.uid('fetch', uids, query)
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/imaplib2.py", line 1167, in uid
    return self._simple_command('UID', command, *args, **kw)
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/imaplib2.py", line 1615, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/imaplib2.py", line 1378, in _command_complete
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/imaplib2.py", line 176, in get_response
    raise typ(exc_fmt % str(val))

ERROR: command: UID => socket error: <class 'socket.error'> - [Errno 54] Connection reset by peer

Traceback:
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/folder/IMAP.py", line 660, in _fetch_from_imap
    res_type, data = imapobj.uid('fetch', uids, query)
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/imaplib2.py", line 1167, in uid
    return self._simple_command('UID', command, *args, **kw)
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/imaplib2.py", line 1615, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/imaplib2.py", line 1378, in _command_complete
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/imaplib2.py", line 176, in get_response
    raise typ(exc_fmt % str(val))

ERROR: Copying message 22004 [acc: Gabriel]
  list.remove(x): x not in list

Traceback:
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/folder/Base.py", line 581, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/folder/IMAP.py", line 267, in getmessage
    self.imapserver.releaseconnection(imapobj)
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/imapserver.py", line 131, in releaseconnection
    self.assignedconnections.remove(connection)
```

Thanks in advance

**Comment by nicolas33** [comment] 2015-05-30 00:18
Please try v6.5.7.

**Comment by gabrielstuff** [comment] 2015-05-30 07:45
Going to this morning !

**Comment by gabrielstuff** [comment] 2015-05-30 08:30
Humm not yet ready through `brew`,  updating the formula locally.

**Comment by gabrielstuff** [comment] 2015-05-30 08:52
Ok synching.... I'll keep you posted in one or two hours.

**Comment by gabrielstuff** [comment] 2015-05-30 12:16
Ok got : 

```
 Copy message 134648 (1734 of 1757) Remote:INBOX -> Local
 Copy message 134649 (1735 of 1757) Remote:INBOX -> Local
 Copy message 134650 (1736 of 1757) Remote:INBOX -> Local
 Copy message 134651 (1737 of 1757) Remote:INBOX -> Local
 Copy message 134652 (1738 of 1757) Remote:INBOX -> Local
 Copy message 134653 (1739 of 1757) Remote:INBOX -> Local
 Copy message 134654 (1740 of 1757) Remote:INBOX -> Local
 Copy message 134655 (1741 of 1757) Remote:INBOX -> Local
Copy message from Remote:INBOX:
 ERROR: IMAP server 'Remote' does not have a message with UID '134654'
Folder INBOX [acc: Gabriel]:
 Copy message 134656 (1742 of 1757) Remote:INBOX -> Local
 Copy message 134657 (1743 of 1757) Remote:INBOX -> Local
 Copy message 134658 (1744 of 1757) Remote:INBOX -> Local
 Copy message 134659 (1745 of 1757) Remote:INBOX -> Local
 Copy message 134660 (1746 of 1757) Remote:INBOX -> Local
 Copy message 134661 (1747 of 1757) Remote:INBOX -> Local
 Copy message 134662 (1748 of 1757) Remote:INBOX -> Local
 Copy message 134663 (1749 of 1757) Remote:INBOX -> Local
 Copy message 134664 (1750 of 1757) Remote:INBOX -> Local
 Copy message 134665 (1751 of 1757) Remote:INBOX -> Local
 Copy message 134666 (1752 of 1757) Remote:INBOX -> Local
 Copy message 134667 (1753 of 1757) Remote:INBOX -> Local
 Copy message 134668 (1754 of 1757) Remote:INBOX -> Local
 Copy message 134669 (1755 of 1757) Remote:INBOX -> Local
 Copy message 134670 (1756 of 1757) Remote:INBOX -> Local
 Copy message 134671 (1757 of 1757) Remote:INBOX -> Local
 Deleting flag F from 159 messages on INBOX
Account sync Gabriel:
 *** Finished account 'Gabriel' in 36:36
ERROR: Exceptions occurred during the run!
ERROR: IMAP server 'Remote' does not have a message with UID '134654'

Traceback:
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/Base.py", line 770, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 278, in getmessage
    data = self._fetch_from_imap(imapobj, str(uid), 2)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 706, in _fetch_from_imap
    raise OfflineImapError(reason, severity)
```

**Comment by nicolas33** [comment] 2015-05-30 15:37
Is this reproducible? If so, is it for the same UID?

**Comment by gabrielstuff** [comment] 2015-05-30 16:15
Nop ! Only happen ones :/ and finally got my emails backuped !

**Comment by nicolas33** [comment] 2015-05-30 16:57
Good to know.

**Comment by gabrielstuff** [comment] 2015-06-06 21:00
Hi, 
Unforntunately, it happen again :/

See related log :

```
Copy message from Remote:INBOX:
 Establishing connection to mail.gandi.net:143
 ERROR: command: UID => socket error: <type 'exceptions.IOError'> - Too many read 0
 ERROR: Copying message 134742 [acc: Gabriel]
  list.remove(x): x not in list
Thread 'Copy message from Remote:INBOX' terminated with exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/threadutil.py", line 163, in run
    Thread.run(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/Base.py", line 770, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 280, in getmessage
    self.imapserver.releaseconnection(imapobj)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imapserver.py", line 162, in releaseconnection
    self.assignedconnections.remove(connection)
ValueError: list.remove(x): x not in list


Last 4 debug messages logged for Copy message from Remote:INBOX prior to exception:
thread: Register new thread 'Copy message from Remote:INBOX' (account 'Gabriel')
imap: Using STARTTLS connection
imap: Attempting PLAIN authentication
imap: __plainhandler: returning gabriel@soixantecircuits.fr
ERROR: Exceptions occurred during the run!
ERROR: command: UID => socket error: <type 'exceptions.IOError'> - Too many read 0

Traceback:
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 685, in _fetch_from_imap
    res_type, data = imapobj.uid('fetch', uids, query)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 1176, in uid
    return self._simple_command('UID', command, *args, **kw)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 1633, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 1393, in _command_complete
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 188, in get_response
    raise typ(exc_fmt % str(val))

ERROR: Copying message 134742 [acc: Gabriel]
  list.remove(x): x not in list

Traceback:
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/Base.py", line 770, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 280, in getmessage
    self.imapserver.releaseconnection(imapobj)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imapserver.py", line 162, in releaseconnection
    self.assignedconnections.remove(connection)
```

I'll be happy to help @nicolas33 if you need anything...

I'm using mail.gandi.net as mail server.

Thanks

**Comment by holymonson** [comment] 2015-08-11 04:18
It seems very easy to reproduce in my situation, where network latency is over 500ms. I have set the -1 option to disable multithreading.

```
 Copy message 227292 (87 of 859) XXX-remote:INBOX -> XXX-local
 Establishing connection to mail.corp.XXX.com:993
 ERROR: command: UID => socket error: <type 'exceptions.IOError'> - Too many read 0
 Establishing connection to mail.corp.XXX.com:993
 ERROR: command: UID => socket error: <type 'exceptions.IOError'> - Too many read 0
 ERROR: Copying message 227292 [acc: XXX]
  list.remove(x): x not in list
 ERROR: Syncing folder INBOX [acc: XXX]
  list.remove(x): x not in list
 ERROR: ERROR in syncfolder for XXX folder INBOX: Traceback (most recent call last):
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/accounts.py", line 567, in syncfolder
    remotefolder.syncmessagesto(localfolder, statusfolder)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/Base.py", line 979, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/Base.py", line 853, in __syncmessagesto_copy
    register = 0)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/Base.py", line 770, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 280, in getmessage
    self.imapserver.releaseconnection(imapobj)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imapserver.py", line 162, in releaseconnection
    self.assignedconnections.remove(connection)
ValueError: list.remove(x): x not in list

  list.remove(x): x not in list
 Syncing INBOX/10F Renovation: IMAP -> Maildir
```

**Comment by holymonson** [comment] 2015-08-13 10:11
A dirty hack with the below patch somewhat works (error but no hung), and I also raise `rxzero` upper limit to 100 instead of 5.

```
--- /Users/monson/project/offlineimap/offlineimap/imapserver.py	2015-08-13 18:03:03.000000000 +0800
+++ /usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imapserver.py	2015-08-13 16:34:03.000000000 +0800
@@ -159,7 +159,10 @@

         if connection is None: return #noop on bad connection
         self.connectionlock.acquire()
-        self.assignedconnections.remove(connection)
+        try:
+            self.assignedconnections.remove(connection)
+        except ValueError:
+            pass
         # Don't reuse broken connections
         if connection.Terminate or drop_conn:
             connection.logout()
```

**Comment by holymonson** [comment] 2015-08-14 04:36
Additionally, above patch only works in single threading, it will raise fatal exception and exit in multi threading.

```
Copy message from XXX-remote:Sent:
 Establishing connection to mail.corp.XXX.com:993
 ERROR: command: UID => socket error: <type 'exceptions.IOError'> - Too many read 0
 ERROR: Copying message 38971 [acc: XXX]
  command: UID => socket error: <type 'exceptions.IOError'> - Too many read 0
Copy message from XXX-remote:Lena/memo-list:
 Establishing connection to mail.corp.XXX.com:993
Folder Lena/memo-list [acc: XXX]:
 Copy message 174252 (16 of 12169) XXX-remote:Lena/memo-list -> XXX-local
Thread 'Copy message from XXX-remote:Sent' terminated with exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/threadutil.py", line 163, in run
    Thread.run(self)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/Base.py", line 770, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 278, in getmessage
    data = self._fetch_from_imap(imapobj, str(uid), 2)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 695, in _fetch_from_imap
    raise e
abort: command: UID => socket error: <type 'exceptions.IOError'> - Too many read 0


Last 7 debug messages logged for Copy message from XXX-remote:Sent prior to exception:
thread: Register new thread 'Copy message from XXX-remote:Sent' (account 'XXX')
imap: Attempting GSSAPI authentication
imap: Attempting PLAIN authentication
imap: __plainhandler: returning YYY
imap: Attempting GSSAPI authentication
imap: Attempting PLAIN authentication
imap: __plainhandler: returning YYY
ERROR: Exceptions occurred during the run!
ERROR: command: UID => socket error: <type 'exceptions.IOError'> - Too many read 0

Traceback:
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 685, in _fetch_from_imap
    res_type, data = imapobj.uid('fetch', uids, query)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 1176, in uid
    return self._simple_command('UID', command, *args, **kw)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 1633, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 1393, in _command_complete
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 188, in get_response
    raise typ(exc_fmt % str(val))

ERROR: command: UID => socket error: <type 'exceptions.IOError'> - Too many read 0

Traceback:
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 685, in _fetch_from_imap
    res_type, data = imapobj.uid('fetch', uids, query)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 1176, in uid
    return self._simple_command('UID', command, *args, **kw)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 1633, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 1393, in _command_complete
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 188, in get_response
    raise typ(exc_fmt % str(val))

ERROR: command: UID => socket error: <type 'exceptions.IOError'> - Too many read 0

Traceback:
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 685, in _fetch_from_imap
    res_type, data = imapobj.uid('fetch', uids, query)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 1176, in uid
    return self._simple_command('UID', command, *args, **kw)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 1633, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 1393, in _command_complete
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/imaplib2.py", line 188, in get_response
    raise typ(exc_fmt % str(val))

ERROR: Copying message 38971 [acc: XXX]
  command: UID => socket error: <type 'exceptions.IOError'> - Too many read 0

Traceback:
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/Base.py", line 770, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 278, in getmessage
    data = self._fetch_from_imap(imapobj, str(uid), 2)
  File "/usr/local/Cellar/offline-imap/6.5.7/libexec/offlineimap/folder/IMAP.py", line 695, in _fetch_from_imap
    raise e
```

**Comment by nicolas33** [comment] 2015-08-14 12:10
I'm not sure what to do about this patch. This is hiding the root cause.

**Comment by renard** [comment] 2015-11-03 20:37
As far as I can test the issue is in `imaplib2` line 2649:

```
self.sock.shutdown(socket.SHUT_RDWR)
```

The problem does not happen when only closing the writer side using `SHUT_WR`. This means for some reason the reader side has been shutdown. I cannot see why.

Is there a reason shutting down both sides since the `finally` block does a `close()`?

**Comment by renard** [comment] 2015-11-03 23:02
This patch work for me:


```patch
modified   offlineimap/imaplib2.py
old mode 100644
new mode 100755
@@ -578,7 +578,11 @@ class IMAP4(object):
         Close I/O established in "open"."""
 
         try:
-            self.sock.shutdown(socket.SHUT_RDWR)
+            self.sock.shutdown(socket.SHUT_WR)
+            try:
+                self.sock.shutdown(socket.SHUT_RD)
+            except:
+                pass
         except OSError as e:
             # The server might already have closed the connection
             if e.errno != errno.ENOTCONN:
```

This is correct since the `LOGOUT` command has already been sent and this bug seems to be MacOSX specific I guess this is because internally `SHUT_RDWR` is done in 2 steps.

What I don't understand is that in V6.5.7 the behaviour is different (i haven't diff all the code though).


From Python doc:

> Shut down one or both halves of the connection. If how is SHUT_RD, further
> receives are disallowed. If how is SHUT_WR, further sends are disallowed. If
> how is SHUT_RDWR, further sends and receives > are disallowed. Depending on
> the platform, shutting down one half of the connection can also close the
> opposite half (e.g. on Mac OS X, shutdown(SHUT_WR) does not allow further
> reads on the other end of the connection).

**Comment by nicolas33** [comment] 2015-11-03 23:29
imaplib2 is embedded tierce library owned by Piers. The official project is there: http://sourceforge.net/projects/imaplib2/?source=navbar

@renard: Please, open an issue and send your patch upstream so it gets merged there. Once done, we'll take the new version.

**Comment by renard** [comment] 2015-11-04 00:14
I cannot open an issue on SF. I send a mail directly to Piers (you are in copy).

**Comment by nicolas33** [comment] 2016-05-11 02:30
There are different issues in this thread. I'm closing. Please make a new one for each if still reproducible.

**Closed by nicolas33** 2016-05-11 02:30 UTC
Labels: bug, need contributor!
