### ISSUE TITLE
Duplicates of messages copied from remote to local

### ISSUE THREAD

**Issue by elliotkendall** [OfflineIMAP/offlineimap#174] opened 2015-03-09 18:20 UTC
I have been running offlineimap for going on a month now, and every week or so I see an issue where it will begin downloading two copies of each incoming message. Quitting and re-starting offlineimap fixes the problem. I am using offlineimap in combination with davmail to access an Office365 mailbox, but I don't think the problem is in that end since restarting offlineimap fixes it.

Here's my .offlineimaprc:

    [general]
    accounts = davmail
    
    [Account davmail]
    localrepository = Local
    remoterepository = Remote
    autorefresh = 1
    postsynchook = ~/bin/offlineimap-notmuch-hook
    
    [Repository Local]
    type = Maildir
    localfolders = ~/.mail/
    
    [Repository Remote]
    type = IMAP
    remotehost = localhost
    remoteport = 1143
    remoteuser = ...
    keepalive = 60
    holdconnectionopen = yes
    idlefolders = ['INBOX']
    folderfilter = lambda foldername: foldername in ['INBOX']

**Comment by hobarrera** [comment] 2015-05-20 17:40
I've been using offlineimap for over two years.
Recently (this first ocurred two days ago), my INBOX gets all the messages duplicated. The duplicates are stored locally, but are not synced upstream.

Deleting the local status file and the INBOX results in a clean re-sync, but after some hours, everything gets duped again.

I first noticed the issue some hours after upgrading to  6.5.7, which was on 2015-05-18 04:24.

I'm using offlineimap with dovecot upstream, so I think we can discard davmail as the guilt party (as this seems to be the same issue).

**Comment by hobarrera** [comment] 2015-05-20 17:41
Also note that *all* messages in my INBOX are duplicated, not only new ones. Emails from back to 2013 get dupped, but *not* immediately after the first sync.

**Comment by hobarrera** [comment] 2015-05-20 18:18
Restaring offlineimap does not trigger the issue. I'd bisect this, but I can't seem to find what triggers it yet.
I'll be happy to if somebody finds the cause.

**Comment by elliotkendall** [comment] 2015-05-21 01:13
Maybe not the same bug, then. When I have this problem, it's only new messages that get duplicated.

**Comment by RoganDawes** [comment] 2015-10-29 13:37
I'm also seeing this bug. So far, offlineimap has duplicated some messages as many as 4 times over. Any ideas?

**Comment by nicolas33** [comment] 2015-10-29 15:22
I've seen this but myself a while back, too. It was not too much offending here. It happened without IDLE on successive usual syncs.
Anyway, I won't fix this myself because I'm putting my efforts into imapfw.

**Comment by RoganDawes** [comment] 2015-10-31 00:03
So I did a little spelunking through my mailbox, and found that in some cases, I have as many as 7 copies! What was interesting for me was the dates on the files, though:

$ grep "F2907E9B-CBC9-4D43-B37A-148AF352D35B" ~/tmp/INBOX.Message-Id | cut -f1-2 -d: | xargs ls -l
Mar 12  2015 ./cur/1426167450_0.94652.Hera.local,U=41284,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,RS
May 29 06:33 ./cur/1432899182_0.54893.Hera.local,U=41284,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,RS
Jul 14 04:57 ./cur/1436867872_5.25680.Hera.local,U=41284,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,RS
Sep 28 08:13 ./cur/1443446032_0.1108.user96.sp-hbn.com,U=41284,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,RS
Oct 14 01:26 ./cur/1444803960_0.80804.Hera-2.local,U=41284,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,RS
Oct 26 04:42 ./cur/1445852558_0.1846.hera.local,U=41284,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,RS
Oct 29 04:11 ./cur/1446109907_0.2698.hera.local,U=41284,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,RS

The dates indicate that this has been going on for quite a while. In fact, my offlineimaprc file has a modification date of 7 May, which is when I changed it to use IMAP IDLE to monitor my inbox.

What may also be related is the fact that the hostname has changed, for example, when doing DHCP from different servers, or moving around between networks. As a result, the filename is also different, even though it appears to have the MD5 sum of the contents(?) or similar embedded in it.

I don't know if that is the answer, but it might point to it, perhaps.

**Comment by elliotkendall** [comment] 2015-10-31 05:31
Interesting insight, but I (1) never had more than a single duplicate at at time, and (2) never changed hostname. Maybe there's more than one bug here.

**Comment by hobarrera** [comment] 2015-10-31 05:45
I've had duplicates, and quadruplicates on different occasions. I don't recall ever seeing three copies of a message, if that can be of any use.

I've always had IDLE active, since that's really the feature that I care about the most.

**Comment by nicolas33** [comment] 2015-10-31 12:52
I don't think the hostname change is related to the issue. Now, I'm not sure the duplicates I've had came from OfflineIMAP. It really looks like it's an IDLE issue.

**Comment by hobarrera** [comment] 2015-10-31 19:29
I have *never* changed the hostname for any of the hosts that exhibited the issue, so it cannot be related to the issue (unless they're different issues).

**Comment by vleonbonnet** [comment] 2015-11-29 04:40
I have experienced this issue as well. I usually don't get duplicate emails because I use the sqlite backend, which results in OfflineIMAP crashing because of duplicate primary keys ("PRIMARY KEY must be unique").

Spent a few minutes over the code and the issue seems logical, I see two sets of threads operating independently, one set is tied the account (https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap/accounts.py#L351) and another set of is tied to the idle feature (https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap/imapserver.py#L749). They both call the syncfolder method, and eventually they both run it at the same time.

I could fix the code, but I'm not quite sure what should be expected behavior here. I could see several options to fix this:
1. Folders beeing watched by the idle thread should not be included in regular account syncs.
2. The idle feature should not sync but just instruct the account to do start a new sync.
3. Both syncs can run independently but some locking mechanism should be in place.

For now I'm just going to disable my idle folder.

**Comment by hobarrera** [comment] 2015-11-29 05:24
> 1. Folders beeing watched by the idle thread should not be included in regular account syncs.

Does IDLE notify of flag changes to already present messages and similar stuff? If so, this makes sense the most, and seems like the cleanest solution.

> 2. The idle feature should not sync but just instruct the account to do start a new sync.

Syncing the whole account seems kinda heavy - especially if there are a lot of mailboxes, since you'd refresh every one each time an email get into the IDLE account. I'm not very convinced about this alternative.

> 3. Both syncs can run independently but some locking mechanism should be in place.

If option (1) syncs everything (flag statuses, etc), then it seems the simplest. This seems like the most complex solution, but I'd still prefer it over option 2.

**Comment by vleonbonnet** [comment] 2016-02-09 08:59
FYI I went with the workaround explained in this article [http://offlineimap.org/configuration/2016/01/29/why-i-m-not-using-maxconnctions.html](url) because the author clearly states that multithreading in offlineimap is broken. So don't expect me to fix this bug.

**Comment by nicolas33** [comment] 2016-02-09 13:55
@vleonbonnet : should we understand the workaround is working for you?

**Comment by vleonbonnet** [comment] 2016-02-09 18:39
As far as I understand this issue, the root cause is that there are two threads calling the same function at the same time, and that function is not thread-safe. Instead of patching the code, I decided to follow the advice of removing all multithreading from offlineIMAP and run several instances (I have multiple email accounts) for concurrency. Turns out you generally don't need to enable the IDLE feature on more than one folder (INBOX), so for now this workaround works for me, yeah (minus a smaller IDLE issue, which is not relevant to this ticket.)

**Comment by nicolas33** [comment] 2016-02-09 23:28
@vleonbonnet Ok, thanks you.

**Comment by a3nm** [comment] 2016-02-11 13:08
I also encountered this issue, which duplicated all mail in my inbox a few times. It is quite annoying.

I'm trying the workaround of not including "maxconnections".

More generally, I'm quite surprised that offlineimap offers options to enable multithreading, if it is known to be broken and cause bugs of this magnitude.

**Comment by nicolas33** [comment] 2016-02-11 14:38
@a3nm: I understand. As I tried to explain in the blog post, the options are there for historical reasons. They are still available because they might be required for some configuration or users wanting to use the (still experimental) IDLE feature.

**Comment by a3nm** [comment] 2016-02-11 14:40
OK I get it, thanks for explaining! That said, maybe the threading options and/or IDLE should show up big warnings to indicate that they suffer from severe and known bugs. It's one thing to say that they are experimental, it's another thing to say that they are known to be badly broken. :)

**Comment by nicolas33** [comment] 2016-02-11 16:40
This is explained [in the manual](https://github.com/OfflineIMAP/offlineimap/blob/master/docs%2Fofflineimap.txt#L323) and we encourage users to read the section dedicated to the known issues [in the configuration file](https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L894) for the IDLE option.

**Comment by nicolas33** [comment] 2016-07-23 01:03
Could you test v7.0.0, please?

**Comment by nicolas33** [comment] 2016-09-08 18:06
I think this error and #174 have the same root cause. I'm closing this one because we had no more feedback here. Also, working with latest versions help.

**Closed by nicolas33** 2016-09-08 18:06 UTC
Labels: bug, IDLE, waiting submitter feedback

**Comment by a3nm** [comment] 2016-09-09 10:48
Sorry I haven't been giving feedback. I'm running the offlineimap version from Debian, which is not 7.0.0 yet (it's currently 6.7.0.1), and I didn't find the time to try installing manually a new version...

That said, I don't think I've seen the problem recur since I removed the "maxconnections" setting.

**Comment by nicolas33** [comment] 2016-09-09 14:58
@a3nm Ok, thank you.
