### ISSUE TITLE
ncurses flicker with blinkenlights UI

### ISSUE THREAD

**Issue by tblancher** [OfflineIMAP/offlineimap#290] opened 2016-01-06 13:13 UTC
I'm running Arch Linux, with Offlineimap 6.6.1 in a tmux session, and I saw the problem in 6.5.7.  The problem existed in Debian as well, but when I moved to Arch the problem was fixed for a time. The blinkenlights UI will flicker, both the ncurses window header and the actual offlineimap output.  I made an Arch Linux forum post with animated GIFs demonstrating the problem:

https://bbs.archlinux.org/viewtopic.php?id=204255

The same version (6.6.1) works on OS X with iTerm2, but iTerm2 demonstrates the issue when logged into my Arch system.  The terminal emulator terminology doesn't exhibit the flicker, but offlineimap keeps replacing the first line of output with the next line (with only one line displayed besides the header and footer).

I usually use the basic interface as a workaround, but it's harder to read because there are no colors.  ttyui has similar issues to #160, but they can usually be overcome by a tmux session exit and relaunch.  If I run "offlineimap -u blinkenlights" in the Python debugger (pdb), the process never appears to exit, and I don't know how to get a stack trace with it.  The gdb stack trace doesn't appear useful on my system.

How can I help debugging this?

**Comment by nicolas33** [comment] 2016-01-06 16:31
![3xl7opn](https://cloud.githubusercontent.com/assets/90065/12147801/0efeee72-b49b-11e5-96fc-79ff29976080.gif)

Attached your gif here.

Since it worked for you before, you should git bisect the issue. I wonder if a ncurses update is to blam, though.

**Comment by chneukirchen** [comment] 2016-03-11 15:51
I tracked this down to ncurses 6, with 5.9 it worked fine for me.

**Comment by nicolas33** [comment] 2016-03-11 16:29
Might worth reporting this to ncurses, then.

**Comment by chneukirchen** [comment] 2016-03-11 16:53
What happens here is that getch() returns nonstop KEY_RESIZE.

**Comment by nicolas33** [comment] 2016-03-11 17:07
Is there something we can do to handle this cleanly in offlineimap?

**Comment by chneukirchen** [comment] 2016-03-11 17:15
Perhaps its a threading issue. When I trace all wgetch() calls from gdb, it always returns KEY_RESIZE. But when I inject a wgetch(stdscr) call from gdb, after a few KEY_RESIZE it returns to -1 or the actual key pressed...

**Comment by nicolas33** [comment] 2016-03-11 17:57
Maybe there's a way to wrap the relevant calls with a threading lock to check how it turns out.

**Comment by jtsymon** [comment] 2016-03-12 03:11
So apparently force pushing to update a commit spams any referenced issues with messages.
Sorry.

**Comment by nicolas33** [comment] 2016-03-12 07:57
That's a new behaviour, but a good one! Now, I wonder what happens to the comments.
C.f. http://www.offlineimap.org/github,/pull/requests/2016/03/08/github-pr-suck.html

**Comment by chneukirchen** [comment] 2016-03-13 19:50
Ok, I think an easier solution would be to just use `curses.resize_term` instead of `curses.resizeterm`.
The latter does not ungetch an KEY_RESIZE.

**Comment by nicolas33** [comment] 2016-03-13 19:52
I have no idea, sorry. I don't use the ncurse UI myself and I didn't play with it. If you try it out and you find it better, I'm willing to merge the change.

**Comment by chneukirchen** [comment] 2016-03-13 19:59
That seems to work just as well as it did with 5.9 (which is to say, doesn't work perfect, but it doesnt redraw infinitely at least).

We can propose this to Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=809676 to get more testers perhaps.

**Comment by nicolas33** [comment] 2016-03-13 20:13
It's up to you to propose it at Debian.
If it worked better before, I wonder why that was changed though.

**Comment by chneukirchen** [comment] 2016-03-13 20:20
FTR, the upstream change is

```
    ncurses 5.9 - patch 20120707
    
    + add ncurses_mingw.h to installed headers (prompted by patch by
      Juergen Pfeifer).
    + clarify return-codes from wgetch() in response to SIGWINCH (prompted
      by Novell #769788).
    + modify resizeterm() to always push a KEY_RESIZE onto the fifo, even
      if screensize is unchanged.  Modify _nc_update_screensize() to push a
      KEY_RESIZE if there was a SIGWINCH, even if it does not call
      resizeterm().  These changes eliminate the case where a SIGWINCH is
      received, but ERR returned from wgetch or wgetnstr because the screen
      dimensions did not change (Novell #769788).
```

**Comment by chneukirchen** [comment] 2016-03-13 20:20
So strictly speaking, I think offlineimap used the function wrong.

**Comment by nicolas33** [comment] 2016-03-13 20:22
Ok, I get it. Any change must be compatible for both ncurse < 5.9 and >= 6.0.
Not easy to test for both, I know. :-/

**Comment by chneukirchen** [comment] 2016-03-14 12:07
It will work on 5.9 just as well.

**Comment by gaudenz** [comment] 2016-04-08 07:19
Coming here from the Debian bug report: @chneukirchen Is there a proposed patch to test? I tried the patch below. While this fixes the flickering it breaks the redrawing of the UI. The UI still looks quite broken and definitely worse than before the ncurses update.
```
--- ui/Curses.py.orig	2016-04-08 09:05:14.900756643 +0200
+++ ui/Curses.py	2016-04-08 09:05:40.904876953 +0200
@@ -570,7 +570,7 @@
         self.height, self.width = self.stdscr.getmaxyx()
         self.logheight = self.height - len(self.accframes) - 1
         if resize:
-            curses.resizeterm(self.height, self.width)
+            curses.resize_term(self.height, self.width)
             self.bannerwin.resize(1, self.width)
             self.logwin.resize(self.logheight, self.width)
         else:
```

**Comment by nicolas33** [comment] 2016-04-08 12:31
I think https://github.com/OfflineIMAP/offlineimap/issues/290#issuecomment-196036356 has tips about what to do. ,-)

**Comment by gaudenz** [comment] 2016-04-09 11:03
@nicolas33 @chneukirchen The patch does he obvious part of that comment. But what is exactly meant by " possibly force a redraw afterwards." I had a quick look at the code, but it was not very obvious how to force a redraw.
I also don't understand "The latter function will not ungetch an KEY_RESIZE, resulting in this nasty loop." but this may due to the fact that I'm not really familiar with ncurses programming. From the python documentation https://docs.python.org/2/library/curses.html#curses.resize_term it seems to me that curses.resizeterm is the right function to use. So I'm not sure about the proposed solution.

**Comment by iliastsi** [comment] 2016-10-14 14:26
I created a [patch](https://github.com/iliastsi/offlineimap/commit/d48663b9bf94ef02e381b6800b79574b6b9e2d6c) that hopefully fixes this. Since I do not use Blinkenlights myself, I would like more people to test this, before submitting a PR. Please let me know. Thanks.

**Comment by tblancher** [comment] 2016-10-15 00:40
Ilias,

Unfortunately I think this patch is moot.  Offlineiamp 7.x has removed
blinkenlights from the UI options.

Trey Blancher
trey@blancher.net

**Comment by iliastsi** [comment] 2016-10-15 07:07
Hi Trey,

On Fri, Oct 14, 2016 at 05:40PM, tblancher wrote:
> Unfortunately I think this patch is moot.  Offlineiamp 7.x has removed
> blinkenlights from the UI options.

This was a regression and has been fixed in the latest version of
OfflineIMAP (v7.0.8). See #381 for the fix.

**Comment by chneukirchen** [comment] 2016-10-15 16:20
OfflineIMAP (v7.0.8) has the same bug here. https://github.com/iliastsi/offlineimap/commit/d48663b9bf94ef02e381b6800b79574b6b9e2d6c fixes it for me. Thanks!

**Comment by nicolas33** [comment] 2016-10-18 12:55
Ok. I'll take the patch when @iliastsi think it's time for the PR.

**Comment by nicolas33** [comment] 2016-10-20 12:14
Fixed by @iliastsi.

**Closed by nicolas33** 2016-10-20 12:14 UTC
Labels: bug, need contributor!
