### ISSUE TITLE
ERROR: IMAP server 'Server Remote' does not have a message with UID 'xxx'

### ISSUE THREAD

**Issue by vbalnt** [OfflineIMAP/offlineimap#62] opened 2013-10-24 01:29 UTC
There are a number of emails in my mailbox that constantly raise the exception below

`raise OfflineImapError(reason, severity)`

The errors are something like

`ERROR: IMAP server 'Server ### Remote' does not have a message with UID 'xxx'`

Any idea on what's going on?

This is with version 6.5.5

**Comment by nicolas33** [comment] 2015-01-10 01:46
There is no easy hack because only a human can confirm the unexpected change is valid and how to recover from it.

That beeing said, this error is frequent enough to improve the recovering for easy cases.

**Comment by dispanser** [comment] 2015-05-21 06:47
is there a way to manually resolve this, given just the error message with UUID?

**Comment by deepfire** [comment] 2015-07-24 21:39
This issue makes `offlineimap` basically unusable with MS Exchange.

**Comment by blindmelon** [comment] 2015-10-02 09:32
Anyone got a solution to this - I'm trying to sync with an account I've never used before (uses Exchange) and I'm being held back by this error.

**Comment by nicolas33** [comment] 2015-10-02 11:17
Once the user validates the UID change, it's should not be so hard to automate the recovering in the easy case: it's the matter of programming what's you would do manually as explained in the doc. http://offlineimap.org/doc/FAQ.html#what-is-the-uid-validity-problem-for-folder

IMAP RFC says the UID changes should be avoided as much as possible in order to defect the clients at least as possible. What is different with MS Exchange so that it makes OfflineIMAP unusable?

**Comment by deepfire** [comment] 2015-11-10 12:47
@nicolas33, I'm not sure what is the cause, but the effect is that an immediately initiated re-sync takes about an hour, for a 2k-message mailbox.  It seems to re-do a huge amount of work on each sync.

And actually, I'm not even sure if the result of the sync contains all the mails that are stored on the server -- indeed, I have reasons to suspect otherwise..

**Comment by kucharskim** [comment] 2016-01-27 22:25
I see the same on Exchange mail server:

```
% offlineimap -1 -d imap -l debug.log
...
2016-01-27 22:18:16 DEBUG: Message list for IMAP[INBOX] loaded: 4960 messages
2016-01-27 22:18:16 DEBUG: Syncing messages IMAP[INBOX] -> Maildir[INBOX]
2016-01-27 22:18:16 INFO: Copy message 20004 (1 of 6) Remote:INBOX -> Local
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.06 Account sync Work [async] UID ('FETCH', '20004', '(BODY.PEEK[])')
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.06 Account sync Work state_change_pending.acquire
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.06 Account sync Work state_change_pending.release
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.06 Account sync Work _request_push(NODF72, UID, {}) = NODF72
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.06 Account sync Work data=NODF72 UID FETCH 20004 (BODY.PEEK[])
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.06 Account sync Work UID:NODF72.ready.wait
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.06 mail.example.com writer > NODF72 UID FETCH 20004 (BODY.PEEK[])\r\n
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.40 mail.example.com reader poll => [(5, 1)]
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.40 mail.example.com reader rcvd 28
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.40 mail.example.com reader < NODF72 OK FETCH completed.\r\n
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.40 mail.example.com handler _put_response(NODF72 OK FETCH completed.)
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.40 mail.example.com handler _request_pop(NODF72, ('OK', ['FETCH completed.'])) [0] = NODF72
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.41 mail.example.com handler UID:NODF72.ready.set
2016-01-27 22:18:16 DEBUG: [imap]:   18:16.41 mail.example.com handler state_change_free.set
2016-01-27 22:18:16 ERROR: ERROR: IMAP server 'Remote' does not have a message with UID '20004'
2016-01-27 22:18:16 ERROR: ['  File "/usr/local/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 787, in copymessageto\n    message = self.getmessage(uid)\n', '  File "/usr/local/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 285, in getmessage\n    data = self._fetch_from_imap(str(uid), 2)\n', '  File "/usr/local/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 730, in _fetch_from_imap\n    raise OfflineImapError(reason, severity)\n']
```

I have many messages in IMAP server which end with above error. I didn't look yet what exactly those messages contain. Am I right, reading above log messages, that offlineimap actually fetches the message and then fails with the error?

**Comment by nicolas33** [comment] 2016-01-28 09:33
On Wed, Jan 27, 2016 at 02:25:01PM -0800, kucharskim wrote:

>    I have many messages in IMAP server which end with above error. I
>    didn't look yet what exactly those messages contain. 

Do you have mail with subject like "IMAP server 'Remote' does not have a
message with UID '20004'"?

Otherwise, here's how you could get samples:

1. Create a new folder on server.
2. folderfilter this folder with OfflineIMAP.
3. On server, move more or less mails to this folder until you get the
error.
4. Remove one or more mails until the offending mail is known.

Having more than one sample would be great.

>                                                         Am I right,
>    reading above log messages, that offlineimap actually fetches the
>    message and then fails with the error?

AFAICT, the offending mails aren't fetches at all. I can't reporoduce
this error to check, though.

-- 
Nicolas Sebrecht

**Comment by kucharskim** [comment] 2016-01-29 18:20
@nicolas33, I don't have any message with subject `IMAP server 'Remote' does not have a message with UID '20004'`. However this is what I see connecting via openssl(1) to the Exchange via IMAP:

```
00004 SELECT INBOX
* 2556 EXISTS
* 0 RECENT
* FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
* OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
* OK [UNSEEN 1] Is the first unseen message
* OK [UIDVALIDITY 170535] UIDVALIDITY value
* OK [UIDNEXT 23072] The next unique identifier value
00004 OK [READ-WRITE] SELECT completed.
00005 UID FETCH 20004 (BODY.PEEK[])
00005 OK FETCH completed.
```

No other output, that's why in `offlineimap/folder/IMAP.py` function `_fetch_from_imap()` variable `data` equals to `[None]` and `res_type` equals to `'OK'`. If I do following command:

```
0007 UID FETCH 20004 (BODY[])
* 280 FETCH (BODY[] {736}
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
From: Microsoft Exchange Server 2010
To: Mikolaj Kucharski <usename@example.com>
Subject: Retrieval using the IMAP4 protocol failed for the following
 message: 20004
Content-Transfer-Encoding: quoted-printable

The server couldn't retrieve the following message:

Subject: "Canceled: Meeting title"
From: "Mikolaj Kucharski" ("XXX")
Sent date: 2/17/2015 10:55:25 AM

The message hasn't been deleted. You might be able to view it using either =
Outlook or Outlook Web App. You can also contact the sender to find out wha=
t the message says.=
 UID 20004 FLAGS (\Seen))
0007 OK FETCH completed.
```

Above message is redacted, but I think you will get what it is. Is there anything what offlineimap could do to ignore that type of messages in smart way?

**Comment by nicolas33** [comment] 2016-01-29 23:19
Looks like exchange is creating a fake mail on the fly. At least, it fakes the original mail.

I don't know what to say. This is so wrong and bad behaviour that I don't know whether to laugh or cry.

So, this is clearly inconsitent with the IMAP RFC by two ways (at least):
* if the server can't provide a mail, it MUST respond with an IMAP ERROR (the **NO** result)
* responding with content to the command `FETCH (BODY[])` and not `UID FETCH (BODY.PEEK[])` is just wrong:

[RFC 3501](https://tools.ietf.org/html/rfc3501#section-6.4.5) clearly stands:
```
      BODY.PEEK[<section>]<<partial>>
         An alternate form of BODY[<section>] that does not implicitly
         set the \Seen flag.
```

Replacing an IMAP ERROR expected at protocol level by a fake mail including some kind of explanations is.... well, OMG! Who is the pretended engineer behind this?

I'm not even sure what to understand from the text of the fake mail:

> The server couldn't retrieve the following message:

Oh, why? Database is corrupt?

> The message hasn't been deleted. You might be able to view it using either =
Outlook or Outlook Web App. 

Ah? Are you joking? Isn't IMAP a **standard** protocol that MUST work with any IMAP client?

Fuck. Please, explain all the exchange admins and customers of exchange/outlook/whatever how buying such product is poor. They don't help the world. Nobody.

Well, I don't know what to do. Replacing the core IMAP command in the code is both welcome (to fix this issue) and somewhat "risky". I'm not sure there's a way to nicely ignore this kind of crazy behaviour.

I'm open to any patch to discuss the pro and cons of fix. Talking with code at this time would be a best.

**Comment by nicolas33** [comment] 2016-01-29 23:36
Could someone report this bug to Microsoft BTW?

**Comment by kucharskim** [comment] 2016-01-30 00:37
I can add that viewing those messages via Outlook Web Access shows that they are calendar related messages. In above case those are cancellation notifications of a meeting. When offlineimap tries to sync my Calendar folder I get hundreds of errors like reported here in this bug report.

Thanks for looking into this, @nicolas33

**Comment by nicolas33** [comment] 2016-01-30 11:02
So, I guess a workaround might be to configure the server to filter calendar reports to a folder and folderfilter this folder in OfflineIMAP. Right?

**Comment by xywei** [comment] 2016-02-03 05:39
What happens in my case is when I run offlineimap with MS Exchange web app open, it returns error like this:

```
 *** Finished account 'Test' in 0:25
ERROR: Exceptions occurred during the run!
ERROR: IMAP server 'Remote' does not have a message with UID '1'

Traceback:
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 787, in copymessageto
    message = self.getmessage(uid)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 285, in getmessage
    data = self._fetch_from_imap(str(uid), 2)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 730, in _fetch_from_imap
    raise OfflineImapError(reason, severity)

ERROR: IMAP server 'Remote' does not have a message with UID '2'

Traceback:
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 787, in copymessageto
    message = self.getmessage(uid)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 285, in getmessage
    data = self._fetch_from_imap(str(uid), 2)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 730, in _fetch_from_imap
    raise OfflineImapError(reason, severity)

```

However, it works fine when I log out from the Outlook web app (I do not have Outlook from MS Office Suite).

**Comment by deepfire** [comment] 2016-02-03 07:59
@nicolas33, most of us, in the corporate environment, dealing with Microsoft Exchange, specifically don't have any influence over server configuration..

**Comment by nicolas33** [comment] 2016-02-03 13:56
I believe OfflineIMAP for MS mail servers need more documentation. This would greatly help other users and new comers.
The tricky parts we know currently stands in this issue and [Thomas' blog post](http://offlineimap.org/server/imap/error/2016/01/27/error-no-such-number.html).

I'd be happy to take patches to improve the documentation on the [website](http://offlineimap.org/doc/website-quick-start.html).

**Comment by kucharskim** [comment] 2016-02-06 12:08
On Sat, Jan 30, 2016 at 03:02:33AM -0800, Nicolas Sebrecht wrote:
> So, I guess a workaround might be to configure the server to filter calendar reports to a folder and folderfilter this folder in OfflineIMAP. Right?

Yes, however I found difficult to categorize those calendar related
messages. As stated in this thread, via IMAP I'm not able to fetch them
and via OWA I can view message headers, but none the message headers
seems distinguished enough to make appropriate server side Exchange
filtering rule.

I decided to delete messages which confuse OfflineIMAP as they were
old messages anyway. For now I'm good.

-- 
best regards
q#

**Comment by tomnor** [comment] 2016-02-19 18:49
At the university of North Carolina they have a [FAQ](http://help.unc.edu/help/exchange-email-and-calendar-faq/#id2518) about Exchange mail servers. One of the frequent questions with answer is

    If I don’t like Outlook, will I still be able to use my old e-mail client?

    You can still use any IMAP compliant client for e-mail only, but at the cost of
    integration with the calendar. You will need to use Outlook or outlook.unc.edu
    for calendar functions.

Another faq is

    I’m a Mac user. What client will I be using?

    Any IMAP client such as Mac Mail or Thunderbird for Mac is compatible with
    Exchange. There is native support for Exchange in Outlook for Mac or if you
    are running Snow Leopard, there is native support for Exchange in Mac Mail,
    iCal and Contacts.

So they seem to speak naturally about exchange being IMAP compatible for usual
mail, but unable to handle calendar items respecting IMAP.

It is reasonable to beleive there is a way to query the server if an item is not
to be fetched over IMAP.

I suggest somebody speak with MS to ask of such a method. By now the question
can be straight to the point. But I will not do it.

**Comment by deepfire** [comment] 2016-02-19 21:44
@tomnor, at this point I'm wondering if using Burp to hijack an SSL session between an Outlook client and an Exchange server is going to be a simpler solution.

**Comment by cdown** [comment] 2016-03-02 18:40
For what it's worth, [isync](http://isync.sourceforge.net/) seems to handle this OK. Where it takes OfflineIMAP around 2 minutes to sync my mail because of all of the missing UIDs, it takes mbsync about 10 seconds. It also doesn't issue any warnings/exceptions, but maybe that's because it has a workaround for this case.

It might be worth looking into how isync is doing it to see how OfflineIMAP can improve its functionality here. Sure, it's a Microsoft bug, but if they're not going to fix it then it needs to happen clientside.

**Comment by nicolas33** [comment] 2016-07-18 17:11
If this helps, there is a new feature to ignore UIDs: http://www.offlineimap.org/configuration/2016/07/18/ignoring-UIDs.html.

**Comment by deepfire** [comment] 2016-07-25 00:40
@nicolas33, do I understand it correctly that the suggested workaround is that users should manually populate this list of missing UIDs?

But what if the server-side messages are in the thousands and the missing UIDs are in the hundreds -- all spread across several folders?

Can this not be automated at all?

**Comment by nicolas33** [comment] 2016-07-25 01:55
> do I understand it correctly that the suggested workaround is that users should manually populate this list of missing UIDs?

Yes, it's a manual operation because offlineimap has no way to know if ignoring the UID is the correct thing to do.

If someone wants something like `ignore_UID_on_errors = yes`, I'd welcome patches.

**Comment by tomnor** [comment] 2016-07-25 20:22
Sounds like an acceptable work-around to me. It was such a long time
since I had this problem now. Once I found that culprit by a manual imap
session, the problem did not come back. I even tried to provoke it once
I think by forwarding some calendar invitation, but there was no error.

In case the problem occur again I will upgrade my offlineimap and try
this out. Thanks.

Nicolas Sebrecht writes:

**Comment by gitfoxi** [comment] 2017-03-20 16:36
In addition to getting the error for which this thread is named, I notice that my `/Outlook/Calendar` folder is populated with messages all having the title:

     Retrieval using the IMAP4 protocol failed for the following message:
     176

With all different numbers, and the contents of the messages look like:

```
The server couldn't retrieve the following message:

Subject: "XXX Meeting - Updated with new WebEx"
From: "X, Lisa" ("/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=F2C6681939864C36AB619C415BCBA64E-X,")
Sent date: 9/16/2014 10:04:45 AM

The message hasn't been deleted. You might be able to view it using either Outlook or Outlook Web App. You can also contact the sender to find out what the message says.
```

**Comment by gitfoxi** [comment] 2017-03-20 16:56
I should also say that though I get the strange messages in `/Outlook/Calendar` on all of my 3 nearly identically-configured computers, only one of the computers gives the error in offlineimap.

The error computer is running offlineimap 7.0.13 and *OSX yosemite.*

The no-error computers are running offlineimap 7.0.13 and *macos sierra*.

That has to be a coincidence, right? What could the OS release have to do with it?

**Comment by gitfoxi** [comment] 2017-03-20 16:58
The old `rm -Rf ~/.offlineimap` trick does not help.

**Comment by gitfoxi** [comment] 2017-03-20 17:03
Work around:

```
[Repository OutlookRemote]
...
folderfilter = lambda folder: folder not in ['Calendar']
```

**Comment by nicolas33** [comment] 2017-03-20 18:49
> I should also say that though I get the strange messages in /Outlook/Calendar on all of my 3 nearly identically-configured computers, only one of the computers gives the error in offlineimap.
> 
> The error computer is running offlineimap 7.0.13 and OSX yosemite.
> 
> The no-error computers are running offlineimap 7.0.13 and macos sierra.
> 
> That has to be a coincidence, right? What could the OS release have to do with it?

Would be interesting to dig into this. I don't think the OS is involved here.

Are they for the same account?

**Comment by gitfoxi** [comment] 2017-03-20 18:58
@nicolas33 Yes. I have .offlineimaprc synchonized.

**Comment by nicolas33** [comment] 2017-03-20 19:36
What are the differences in the `Calendar` directory?

**Comment by gitfoxi** [comment] 2017-03-21 01:06
Tricky to diff between two systems but I did. The difference is only the system with the errors had a few more files under `Calendar/cur` which were pretty unremarkable but here's all of the contents, slightly redacted.

The only thing I notice is that my error message  had mentioned "UID 2469" and I recall that I flaked on the meeting that's given that label; and that she rescheduled it twice, possibly leading to the problem UID  as the same meeting changes contents ... Maybe something to do with the exact moment of synchronization ... seems almost impossible to debug.

```
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
From: Microsoft Exchange Server 2010
To: "Michael.Fox@XXXXX.com>
Subject: Retrieval using the IMAP4 protocol failed for the following message:
 2469
Content-Transfer-Encoding: quoted-printable

The server couldn't retrieve the following message:

Subject: "Debug ategen 4x mode for CN88XX 15K scan vectors"
From: "Lin, Stepfaine" ("/O=3DEXCHANGELABS/OU=3DEXCHANGE ADMINISTRATIVE GRO=
UP (FYDIBOHF23SPDLT)/CN=3DRECIPIENTS/CN=3D03437F3F35424E6DBE0D0C3D3FCB8598-=
LIN, STEPFA")
Sent date: 3/13/2017 1:44:32 PM

The message hasn't been deleted. You might be able to view it using either =
Outlook or Outlook Web App. You can also contact the sender to find out wha=
t the message says.=
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
From: Microsoft Exchange Server 2010
To: "Michael.Fox@XXXXX.com>
Subject: Retrieval using the IMAP4 protocol failed for the following message:
 2473
Content-Transfer-Encoding: quoted-printable

The server couldn't retrieve the following message:

Subject: "Debug ategen 4x for scan 15K in ISElabs PS4"
From: "Lin, Stepfaine" ("/O=3DEXCHANGELABS/OU=3DEXCHANGE ADMINISTRATIVE GRO=
UP (FYDIBOHF23SPDLT)/CN=3DRECIPIENTS/CN=3D03437F3F35424E6DBE0D0C3D3FCB8598-=
LIN, STEPFA")
Sent date: 3/14/2017 12:05:18 PM

The message hasn't been deleted. You might be able to view it using either =
Outlook or Outlook Web App. You can also contact the sender to find out wha=
t the message says.=
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
From: Microsoft Exchange Server 2010
To: "Michael.Fox@XXXXX.com>
Subject: Retrieval using the IMAP4 protocol failed for the following message:
 2475
Content-Transfer-Encoding: quoted-printable

The server couldn't retrieve the following message:

Subject: "DVFS training Session-1  WebEx & CRs"
From: "Keefe, Jim" ("/O=3DEXCHANGELABS/OU=3DEXCHANGE ADMINISTRATIVE GROUP (=
FYDIBOHF23SPDLT)/CN=3DRECIPIENTS/CN=3DAE578997F9944A5D91AF82C065D4001D-KEEF=
E, JIM")
Sent date: 3/15/2017 6:25:06 AM

The message hasn't been deleted. You might be able to view it using either =
Outlook or Outlook Web App. You can also contact the sender to find out wha=
t the message says.=
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
From: Microsoft Exchange Server 2010
To: "Michael.Fox@XXXXX.com>
Subject: Retrieval using the IMAP4 protocol failed for the following message:
 2487
Content-Transfer-Encoding: quoted-printable

The server couldn't retrieve the following message:

Subject: "Loadboard schematics for EMMC and TMP421"
From: "Fox, Michael" ("/O=3DEXCHANGELABS/OU=3DEXCHANGE ADMINISTRATIVE GROUP=
 (FYDIBOHF23SPDLT)/CN=3DRECIPIENTS/CN=3D60D58188297E44D3955DA81AFB4A8529-FO=
X, MICHAE")
Sent date: 3/15/2017 1:20:24 PM

The message hasn't been deleted. You might be able to view it using either =
Outlook or Outlook Web App. You can also contact the sender to find out wha=
t the message says.=
MIME-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
From: Microsoft Exchange Server 2010
To: "Michael.Fox@XXXXX.com>
Subject: Retrieval using the IMAP4 protocol failed for the following message:
 2464
Content-Transfer-Encoding: quoted-printable

The server couldn't retrieve the following message:

Subject: "Setup of VM for RHEL3.7"
From: "Hoon, Tien Ching" ("/O=3DEXCHANGELABS/OU=3DEXCHANGE ADMINISTRATIVE G=
ROUP (FYDIBOHF23SPDLT)/CN=3DRECIPIENTS/CN=3DEB7704A8CC9E4E70896D335D7158B33=
4-TCHOON@XXXXX.com")
Sent date: 3/10/2017 10:12:43 PM

The message hasn't been deleted. You might be able to view it using either =
Outlook or Outlook Web App. You can also contact the sender to find out wha=
t the message says.=
```

**Comment by chris001** [comment] 2017-03-21 19:24
I have a Microsoft 365 Exchange email account dedicated to OfflineIMAP and will share the credentials with @nicolas33 and the rest of the dev/testing team, for manual or automatic testing solutions to this bug and any other bugs.

It'd be a Very Good Thing(tm) to add a few lines to this github `.travis.yml`, to have Travis run tests from many client operating systems, including Mac OS X client command line, to the Microsoft 365 Exchange IMAP server account.  Any runtime error or crash will return a non-zero result or stack trace, which causes Travis-CI to fail, and this prevents github from committing the code with the bug, to the project source tree.

**Comment by nicolas33** [comment] 2017-03-21 20:43
`Calendar` is a specific mailbox that Microsoft seems to not want make IMAP compliant. I won't waste time on this. Users MUST folderfilter this mailbox.

I've added an entry about that in the FAQ. This issue is open since 2013 and I'd still welcome patches if anyone want more advanced ignore rules.

Anyway, I'm closing the bug report.

**Closed by nicolas33** 2017-03-21 20:43 UTC
Labels: bug, Exchange, need contributor!
