### ISSUE TITLE
unexpected termination

### ISSUE THREAD

**Issue by naveen1336** [OfflineIMAP/offlineimap#183] opened 2015-03-26 05:04 UTC
Copy message 7363 (328 of 33308) Remote3:[Gmail]/Important -> Local3
Folder INBOX [acc: GMail3]:
 Copy message 14835 (333 of 34265) Remote3:INBOX -> Local3
Folder  [remote name [Gmail]/All Mail] [acc: GMail3]:
 Copy message 28967 (326 of 43830) Remote3:[Gmail]/All Mail -> Local3
Folder Important [remote name [Gmail]/Important] [acc: GMail2]:
 Copy message 40267 (195 of 31249) Remote2:[Gmail]/Important -> Local2
Folder  [remote name [Gmail]/All Mail] [acc: GMail2]:
 Copy message 47310 (202 of 34488) Remote2:[Gmail]/All Mail -> Local2
Copy message from Remote2:[Gmail]/All Mail:
 Establishing connection to imap.gmail.com:993
Thread 'Copy message from Remote2:[Gmail]/Important' terminated with exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/threadutil.py", line 158, in run
    Thread.run(self)
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Gmail.py", line 290, in copymessageto
    super(GmailFolder, self).copymessageto(uid, dstfolder, statusfolder, register)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 693, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Gmail.py", line 78, in getmessage
    data = self._fetch_from_imap(imapobj, str(uid), 2)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 676, in _fetch_from_imap
    imapobj.select(self.getfullname(), readonly = True)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplibutil.py", line 49, in select
    result = super(UsefulIMAPMixIn, self).select(mailbox, readonly)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1000, in select
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 177, in get_response
    raise typ(exc_fmt % str(val))
OfflineImapError: Server 'imap.gmail.com' closed connection, error on SELECT '[Gmail]/Important'. Server said: command: EXAMINE => socket error: <type 'exceptions.IOError'> - Too many read 0

Last 1 debug messages logged for Copy message from Remote2:[Gmail]/Important prior to exception:
thread: Register new thread 'Copy message from Remote2:[Gmail]/Important' (account 'GMail2')
root@3smails:/home/offlineimap#

**Comment by nicolas33** [comment] 2015-03-26 12:43
* OfflineIMAP version?
* Is this reproducible at the exact same message?
* "Too many read 0" means the network socket couldn't read data. It is right to close the connection at that point.

**Comment by naveen1336** [comment] 2015-03-26 12:48
OfflineIMAP version -v6.5.7-rc2
Is this reproducible at the exact same message- most of the time

**Comment by nicolas33** [comment] 2015-03-26 13:21
Please try reducing the following settings:
* `maxsynaccounts`
* `maxconnections`
What are your current values?

I pretty sure you're hitting a limit of the IMAP server. I don't know where such limit would stand: it could come from a maximum number of sockets, IMAP commands, whatever on a per-IP, per-credential, per-socket basis.

**Comment by nicolas33** [comment] 2015-03-26 13:43
A bit more search suggests that Gmail limit IMAP connections up to 15. This can be quickly hit if you have other IMAP clients involved like Thunderbird, mobile phone(s), and perhaps even the Gmail web interface open.

What makes me seriously think the cause is a Gmail limit is that the failure happens on the SELECT which comes early in the process of syncing a folder. In fact, once the socket open, this is the first thing we do AFAIR.
Here, from the logs above we can clearly see that OfflineIMAP is already downloading messages from "Remote2:[Gmail]/Important" when it tries another (failing) SELECT against this same folder.

**Comment by naveen1336** [comment] 2015-03-26 14:54
currently the maxaccounts = 3 and maxconnection=3 and i reduce to 1 and maxconnection = 3 
then the same error after 3 hours

**Comment by nicolas33** [comment] 2015-03-26 15:15
Try reducing maxconnections again to see how it goes.
Do you own all of those accounts? I mean, can't anyone else use an account at the same time?

Is the 3 hours run time better than before?

May I ask why so many account? Just to know more about the possible use cases of OfflineIMAP.

**Comment by naveen1336** [comment] 2015-03-26 15:41
i am corrently working with my friends who want to develop a gmail backup solution .
yes while reducing the maxaccounts = 1 and it running well. My question is why offlineimap downloading mails slowly i have 10MBPS lease line but downloading is too slow

**Comment by nicolas33** [comment] 2015-03-26 16:02
Can't tell much about why it looks slow. You should check about CPU, I/O and some network metrics like bandwidth, ping delays, jitter, lost packets, etc.

With a lot of accounts, I would expect it faster with one instance per account. And this would help if something goes wrong.

Also, I wouldn't use the autorefresh setting and rather start a new fresh instance once the previous is done.

**Comment by nicolas33** [comment] 2015-03-26 16:04
I'm closing since we are really changing of topic. The mailing list is a much better place to talk about things like that.

**Closed by nicolas33** 2015-03-26 16:04 UTC
