### ISSUE TITLE
Backing up from Zimbra to local: syncing weird files, using all free space

### ISSUE THREAD

**Issue by MartinFFM** [OfflineIMAP/offlineimap#483] opened 2017-06-29 08:38 UTC
Hi *,

I'm not too new to offlineimap, but now facing the first issue, which might be a bug and might be known partly.

What am I doing?
I'm setting up a small Debian in a virtual machine (Hyper-V, VMware or VirtualBox - whatever is possible) to backup two, three mailboxes per installation in local Maildir. For some reasons I have to stay at Jessie for the moment. Everything runs nice and smoothie... But...

The prob:
On a new installation I have to backup two mailboxes from a Zimbra server to local Maildir in Debian. I store the local maildir at /home/user/archiv. Running offlineimap creates subfolders for all folders on Zimbra, all mails are synced. Running a script every 30 minutes via cronjob keeps the folders updated.
After a while (12 to 24 hours) offlineimap runs amok and starts syncing something direct to /home/user/archiv (not to the subfolders).
By "something" I mean some files named like "4000000059521e9d34f292b400df06812b0a.m" with size between some kB and some MB. There is no total amount of synced files, it runs until I stop it. Last time I stopped at 59.255.896 files with an amount about 140GB.

What did I try?
Setup everything new, then:
1. Limited the backup of folders in offlineimap from all to one subfolder. Same behaviour.
2. Downloaded and installed offlineimap from Stretch rep. (7.0.12). Same behaviour.

I searched the web and found some people writing some things about offlineimap and Zimbra, but not finding the point where some probs like mine are described or some solution is shown. So my question is, if this is a known bug and if there is a known solution. Both I did not find in here (github).

Thanks a lote for taking care and esp. for doing great stuff like offlineimap!

Greetz
Martin

#### General informations

- system/distribution (with version):  Debian Jessie (8.8.0)
- (1) offlineimap version (`offlineimap -V`):  6.3.4-1
- (2) offlineimap version (`offlineimap -V`):  7.0.12+dfsg1-2
- Python version: 2.7
- server name or domain: Local only
- CLI options:

**Comment by nicolas33** [comment] 2017-06-29 11:28
Looks like the problem stand on the new system. Since we had no other similar reports I wonder there's a bug in python or a library. Could you try with another distrib in another VM?

**Comment by nicolas33** [comment] 2017-06-29 11:31
I wonder this might come from the network driver of the host, too.

**Comment by nicolas33** [comment] 2017-06-29 11:31
Do you backup all the accounts for the same Zimbra instance?

**Comment by MartinFFM** [comment] 2017-06-29 11:39
Funnily I made one preinstall under Hyper-V and transportet the VHD to other virtualisations. On all the rest (other Hyper-V, VMware, VirtualBox) it works just fine.

For any reason I also made the whole install of the virtual Debian again from the very start and tested it again with same result.

I only have this issue with one of two Zimbra accounts on one single machine. Mail-Op checked the Zimbra-mailbox, everything fine. The second account also causes no problems.

I'm running the same installation two times under VirtualBox, backing up from a Debian mailserver, which is using postfix and dovecot.
One more is running under VMware, backing up some account from a microsoft server (whatever this one is... I didn't care about that before).

Changing distrib is a problem, because I need some software behind offlineimap to archiv the mails in a special way. I will need a bigger time for that, but I'm near to holidays.

**Comment by MartinFFM** [comment] 2017-06-29 11:40
Not to forget:
Basic installation has no VM-Tools, Hyper-V-Tools, VirtualBox-Tools installed. I install them, when I set up the archiv.

**Comment by nicolas33** [comment] 2017-06-29 12:50
> Mail-Op checked the Zimbra-mailbox, everything fine. The second account also causes no problems.

Ok, I think Zimbra is not to blame.

> I only have this issue with one of two Zimbra accounts on one single machine.

I have no idea why one account would work while not the other. However, I'd say the system/VM might have issues.

> Funnily I made one preinstall under Hyper-V and transportet the VHD to other virtualisations. On all the rest (other Hyper-V, VMware, VirtualBox) it works just fine.

The template VM image sounds OK or the other VMs would fail.

> Changing distrib is a problem, because I need some software behind offlineimap to archiv the mails in a special way. I will need a bigger time for that, but I'm near to holidays.

I understand that moving to another distrib can't become a definitive resolution.

For now, we don't know the root cause. So, the idea is to try to identify the root cause by changing layouts and try to reproduce the issue.

**Comment by MartinFFM** [comment] 2017-06-29 13:40
> I understand that moving to another distrib can't become a definitive resolution.
At least it can be a nice test. My feeling tells me to leave the Debian branche of Linux and this would make a prob to me, because I'm not working much outside Debian and its forks. But I'll see...

For now I will transfer the whole setup, which I backuped and move it to another machine. There it can run under Stretch, using VirtualBox. Let's see what happenes then.

Btw.: This mess happend always after shutdown the machine, copying it to external USB-HDD and restarting it. I realize that right now. Shutdown and restart was done with PowerShell and was tested woking before.

**Comment by nicolas33** [comment] 2017-06-29 13:54
> Btw.: This mess happend always after shutdown the machine, copying it to external USB-HDD and restarting it. I realize that right now. Shutdown and restart was done with PowerShell and was tested woking before.

Would be great to stop offlineimap before, then. I've often seen VM forcefully stopped rather than gracefully. I don't know if HDD connected via USB is problematic but this is something to consider and yet another layout that would be good to avoid for new checks.

In the end, I'm convinced offlineimap is not to blame directly. It really looks like it has to do with broken data.

**Comment by MartinFFM** [comment] 2017-06-29 14:32
Offlineimap runs from SATA HDD, not USB HDD. Only once a day all virtual machines are stopped and a backup is made. After that they'll restart. It takes about 20min. All tests showed, that the filesystem is ok.

Offlineimap is only running every 30 minutes. One run only lasts for some seconds, because there is not much change in the postbox. So it would be total accident that this happenes while shutdown.

So another thing to test would be, not to stop the virtual machine... I guess this I will do first...

Be sure, I will not blame anyone for anything :) We do not look for problems, but for solutions. To find a solution which shows that offlineimap works fine and this is not caused by a bug might be the better solution ;)

**Comment by nicolas33** [comment] 2017-09-13 18:22
I'm closing this report. We'll re-open on request.

**Closed by nicolas33** 2017-09-13 18:22 UTC
Labels: bug, waiting submitter feedback
