### ISSUE TITLE
whitespaces in accounts line after upgrade to 7.0.2 (from 6.x)

### ISSUE THREAD

**Issue by grauschnabel** [OfflineIMAP/offlineimap#361] opened 2016-07-28 12:10 UTC
offlineimap v7.0.2, imaplib2 v2.55 (bundled)

Just a small thing, but for completeness:

I had to change my line in the .offlineimaprc from

accounts = a, b, c, d
to
accounts = a,b,c,d

(removing spaces)
which worked before.  not it works again.  Just not so good readable.  Otherwise it tell me like account ' b' does not exit and so on errors. Maybe a string.strip is missing somewhere.

- Martin

**Comment by ordnungswidrig** [comment] 2016-07-28 14:12
I ran into the same issue.

**Comment by chew-z** [comment] 2016-07-28 14:43
+1

**Comment by ordnungswidrig** [comment] 2016-07-28 14:48
I tried to find the root cause but the python is to weak in me.

**Comment by chew-z** [comment] 2016-07-28 14:50
```
OfflineIMAP 7.0.2
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
ERROR: The account ' Gmail' does not exist
ERROR: Exceptions occurred during the run!
ERROR: The account ' Gmail' does not exist
Valid accounts are: Fastmail, Gmail
```

**Comment by chew-z** [comment] 2016-07-28 14:55
This is some nasty bug. For me making changes (removing whitespaces) in .offlineimaprc didn't work. I had to reverse to pre 0.7 version and pin it (in brew).

**Comment by nicolas33** [comment] 2016-07-28 15:47
This is fixed already but will be in v7.0.3.

> This is some nasty bug. For me making changes (removing whitespaces) in .offlineimaprc didn't work. I had to reverse to pre 0.7 version and pin it (in brew).

Ah? Error? Stack trace?

**Comment by okubax** [comment] 2016-07-29 11:24
Removing whitespaces in the accounts line in .offlineimaprc worked for me, otherwise, it gives error:

```
Jul 29 11:58:03 eloha offlineimap[1616]: ERROR: The account ' Gmail' does not exist
Jul 29 11:58:03 eloha offlineimap[1616]: ERROR: The account ' Gmail2' does not exist
Jul 29 11:58:03 eloha offlineimap[1616]: ERROR: The account ' Outlook' does not exist
Jul 29 11:58:03 eloha offlineimap[1616]: ERROR: The account ' Yahoo' does not exist
Jul 29 11:58:03 eloha offlineimap[1616]: ERROR: The account ' Yahoo2' does not exist
Jul 29 11:58:03 eloha offlineimap[1616]: ERROR: The account ' Gmail3' does not exist
```
ArchLinux x86_64
offlineimap 7.0.2-1

**Comment by nicolas33** [comment] 2016-07-29 13:45
Forgive me. The patch was applied after v7.0.2. It will be in the upcoming v7.0.3.

**Comment by nicolas33** [comment] 2016-07-29 13:48
What's weird is that removing the whitespaces didn't help. This is the use case reported by @chew-z  I'd like to know more.

**Comment by chew-z** [comment] 2016-08-01 13:33
I can confirm that I have observed that error also after removing whitespaces in offlineimaprc in versions 7.0.0 and 7.0.2. 
I cannot re-create that problem at the moment because I have removed these versions with brew.

**Comment by nicolas33** [comment] 2016-08-03 10:47
Is this reproducible with v7.0.4?

**Comment by chew-z** [comment] 2016-08-03 13:31
7.0.4 isn't yet released in brew. Config with whitespaces seems to work OK with 7.0.3 for me. I have other errors that should  be fixed by 7.0.4. 

After reading latest blog post on offlineimap.org I am considering joining testers :)

Plus I am in North Sumatra now and with wind this strong it's either internet or power gone and it takes hours before they fix it.

**Comment by git-jls** [comment] 2016-08-03 15:22
I can confirm that a config with and without whitespaces works on 7.0.4.
I can also confirm that removing the whitespace on 7.0.2 does resolve the issue for me, just like @okubax  mentioned.

I do however have a problem retrieving my e-mails after upgrading from 6.x
to 7.0.2 and afterwards 7.0.4.

Currently running:
Arch Linux x86_x64
OfflineIMAP 7.0.4

offlineimap --info output:
[http://sprunge.us/CVhO](url)
My offlineimaprc file:
[https://github.com/git-jls/engima/blob/master/offlineimaprc](url)

**Comment by nicolas33** [comment] 2016-08-04 00:18
After reading latest blog post on offlineimap.org I am considering joining testers :)

@chew-z You're welcome!

@git-jls Please, open a new issue. The sep option should not require quotes, with Py2 at least.

Thank you all for the reports.

**Closed by nicolas33** 2016-08-04 00:18 UTC
Labels: waiting submitter feedback
