### ISSUE TITLE
offlineimap does not perform idle checks during a refresh

### ISSUE THREAD

**Issue by derekschrock** [OfflineIMAP/offlineimap#421] opened 2017-01-04 22:47 UTC
#### General informations

offlineimap does not perform idle checks during a refresh.  Some refreshes can take >2+ minutes to finish depending on the number of updates.

Is it possible for offlineimap to perform idle checks during refresh?

- system/distribution (with version): FreeBSD 11.0-RELEASE amd64

- offlineimap version (`offlineimap -V`): OfflineIMAP 7.0.12

- Python version: 2.7.13
- CLI options: none

#### Configuration file offlineimaprc

[general]
accounts = LOADM

[Account LOADM]
localrepository = Local
remoterepository = Remote
autorefresh = 10

[Repository Local]
type = Maildir
localfolders = ~/mail-offline/

[Repository Remote]
type = IMAP
ssl = yes
sslcacertfile = /usr/local/share/certs/ca-root-nss.crt
...
idlefolders = ['INBOX']

#### Steps to reproduce the error

- During offlineimap refresh (10 minutes from above) receive an email to and idlefolder (INBOX)
- See that idle doesn't check until the refresh is complete

**Comment by nicolas33** [comment] 2017-01-05 22:26
> Steps to reproduce the error
> 
> During offlineimap refresh (10 minutes from above) receive an email to and idlefolder (INBOX)
> See that idle doesn't check until the refresh is complete

AFAIR, offlineimap won't keep the IDLE thread while in a sync but I could be wrong. I'll check what the code does.

I guess this hurts because the emails not known at the beginning of the sync are skipped by both the current sync and the IDLE thread. Hence, the skipped emails have to wait for the next autorefresh timeout to get synced.

I'm not sure enabling both autorefresh and IDLE folders is a good idea. I'm not surprised those feature plays badly together because they were not designed to work with each other. This limitation MUST be documented, at least.

A workaround *might* be to configure two accounts in the configuration file. One dedicated for the IDLE folders **only** and the other for the autorefresh folders where the IDLE folders are filtered. Ideally, the global lock should be lower down to the folder level rather than the current account level. This would ensure there's no side effects with this use case.

**Comment by nicolas33** [comment] 2017-01-07 17:29
> AFAIR, offlineimap won't keep the IDLE thread while in a sync but I could be wrong. I'll check what the code does.

AFAICT, both features are happily ignoring each other. This means the IDLE threads and the syncs might try to do concurrent operations. :-(

Lowering down the locks to the folders would be great. I won't work on this myself, though.

**Comment by altruizine** [comment] 2017-01-26 21:24
I'm not sure how useful an IDLE-only account (without autorefresh) would be. Flag propagations and uploads of new messages (that were moved into the local maildir by a MUA) only happen at refresh time, right?

**Comment by nicolas33** [comment] 2017-01-26 22:10
In IDLE mode, offlineimap starts one IDLE thread per IDLE folder. When a message is received by the idle thread, offlineimap runsr the presynchook, a full sync for this folder and finish with the postsynchook.

By default, the quick mode (no flags sync) is *disabled*. The [code is straightforward enough to be read by non-python users](https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap/imapserver.py#L785).

**Comment by nicolas33** [comment] 2017-01-26 22:16
Forgot to say that IDLE only tracks the remote messages. So no, it won't start any sync for local changes. This feature was never implemented.

However, it should not be hard to add this feature.

**Comment by altruizine** [comment] 2017-02-23 16:21
Another idea could be to avoid IMAP synchronization problems between IDLE threads and the autorefresh thread by not running any sync inside the IDLE thread. Instead, the IDLE thread could notify the autorefresh thread, and the latter would perform the needed refresh for that folder (or, in a crude approximation, for all folders; this should be especially easy to implement using SIGUSR1, right?).

**Comment by altruizine** [comment] 2017-02-24 21:25
I had a go at implementing synchronization between IDLE threads and autorefresh threads by implementing mutex locking of all to-be-synchronized folders, because it turns out that nonsynchronized parallel refreshes from multiple threads can lead to all sorts of nasty behavior.  See #438's commit message.

(My Python may be a bit rusty, so please forgive me any rookie mistakes.)

@derekschrock, could you please try whether this patch fixes your issue as well?

**Comment by derekschrock** [comment] 2017-03-01 00:56
@altruizine This patch does not fix my issue.   Sending an email to an account that watches INBOX via IDLE while a sync is in progress does not update/appear in the IDLE watched INBOX until the sync completes.

It seems that an autorefresh should just ignore IDLE mailboxes?  I see offlineimap updating INBOX during an autorefresh.   Does this mean autorefresh is locking IDLE out of updating?   If autorefresh and IDLE could run in parallel and autorefresh ignored IDLE folders then you should be able to see IDLE updates during and autorefresh?

**Comment by nicolas33** [comment] 2017-03-01 07:44
> @altruizine This patch does not fix my issue. Sending an email to an account that watches INBOX via IDLE while a sync is in progress does not update/appear in the IDLE watched INBOX until the sync completes.

This is the expected behavior with this patch. The missing mail is downloaded once the sync is done rather than missing until the next sync.

> It seems that an autorefresh should just ignore IDLE mailboxes?

Not a bad idea. This is worth a try.

> I see offlineimap updating INBOX during an autorefresh. Does this mean autorefresh is locking IDLE out of updating?

With this patch, yes.

> If autorefresh and IDLE could run in parallel and autorefresh ignored IDLE folders then you should be able to see IDLE updates during and autorefresh?

Yes, as long as there are enough there are enough free "connection threads". Implementing this would need to lower down the connections threads available for the syncs and the IDLE thread would have to sync the IDLE folders only.

The best workaround to do exactly this now is to configure offlineimap the way I've described above:

"A workaround might be to configure two accounts in the configuration file. One dedicated for the IDLE folders only and the other for the autorefresh folders where the IDLE folders are filtered. Ideally, the global lock should be lower down to the folder level rather than the current account level. This would ensure there's no side effects with this use case."

The provided patch do introduce a lock at the folder level. This would need to be improved to use an external lock file to allow the above configuration.

**Comment by nicolas33** [comment] 2017-03-15 22:08
Fixed in v7.0.14 by #438.

**Closed by nicolas33** 2017-03-15 22:08 UTC
Labels: bug, need contributor!
