### ISSUE TITLE
apply foldersort after folderfilter

### ISSUE THREAD

**Issue by lahwaacz** [OfflineIMAP/offlineimap#27] opened 2013-03-17 17:06 UTC
Hi,
the 'foldersort' option doesn't work, it's completely ignored. Also there's no mention of it in man page.

**Comment by nicolas33** [comment] 2015-03-24 08:00
Looked at this and as previously said, it's far from trivial patch. Don't expect changes any time soon.

**Comment by nicolas33** [comment] 2016-06-24 17:53
Both compare feature are:
* mbnames: https://github.com/nicolas33/offlineimap/blob/ns/mbnames-2/offlineimap/mbnames.py#L191
* foldersort: https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap/repository/IMAP.py#L427

I guess there's a way to use the same key sorting for both. I'm using none of those features. Could anyone try to make both identical in behaviour?

Also, I think we might stop supporting the "cmp" way of sorting folder names for Python2.

**Comment by nicolas33** [comment] 2016-11-25 00:07
Instead of 

```
def folder_cmp(lst):
    def inner(x, y):
        if x in lst and y in lst:
            return cmp(lst.index(x), lst.index(y))
        elif x in lst:
            return -1
        elif y in lst:
            return 1
        else:
            return 0
    return inner
```

I think the following code would provide the expected behaviour:

```
def folder_cmp(lst):
    def inner(x, y):
        try:
            return cmp(lst.index(x), lst.index(y))
        except KeyError:
            return 0
    return inner
```

Anyway, since this was not implemented for years, I'm closing. I guess that the benefit don't worth the trouble.

**Closed by nicolas33** 2016-11-25 00:07 UTC
Labels: enhancement, need contributor!

**Comment by lahwaacz** [comment] 2016-11-25 06:21
Your solution does not consider the case when _only one_ of the arguments is not in the list, in which case the result should be either 1 or -1. Hence it is not a correct comparator.

**Comment by nicolas33** [comment] 2016-11-25 12:25
Yes.
