### ISSUE TITLE
offlineimap stuck when syncing from local to remote

### ISSUE THREAD

**Issue by csfreebird** [OfflineIMAP/offlineimap#452] opened 2017-04-05 05:37 UTC
#### General informations
stuck from Local:INBOX to Remote
- system/distribution (with version): 
Ubuntu 16.10
- offlineimap version (`offlineimap -V`): 
OfflineIMAP 7.0.14
- Python version: 
Python 2.7.12+
- server name or domain: 
remotehost = imap.263.net
- CLI options: 
no options,just type offlineimap
#### Configuration file offlineimaprc
```
[general]
accounts = ysten
maxsyncaccounts = 3

[Account ysten]
localrepository = Local
remoterepository = Remote
status_backend = sqlite

[Repository Local]
type = Maildir
localfolders = ~/ystMail

[Repository Remote]
type = IMAP
remotehost = imap.263.net
ssl = yes
remoteuser = chenshu@ysten.com
remotepass = ***
maxconnections = 1
realdelete = no
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
```
```
REMOVE PRIVATE DATA.
```

#### pythonfile (if any)

```
REMOVE PRIVATE DATA.
```

#### Logs, error

```
REMOVE PRIVATE DATA.
```

#### Steps to reproduce the error
run offlineimap, then see the output:
```
$ offlineimap
OfflineIMAP 7.0.14
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync ysten:
 *** Processing account ysten
 Establishing connection to imap.263.net:993 (Remote)
Folder Archive [acc: ysten]:
 Syncing Archive: IMAP -> Maildir
Folder Deleted Messages [acc: ysten]:
 Syncing Deleted Messages: IMAP -> Maildir
Folder Draft [acc: ysten]:
 Syncing Draft: IMAP -> Maildir
Folder Drafts [acc: ysten]:
 Syncing Drafts: IMAP -> Maildir
 Copy message UID 916 (1/1) Remote:Drafts -> Local
 Copy message UID -4 (1/4) Local:Drafts -> Remote
 ERROR: Copying message -4 [acc: ysten]
  While attempting to find UID for message with header X-OfflineIMAP, got wrong-sized matchinguids of ['SEARCH', 'search', 'error:', "can't", 'search', 'that', 'criteria']
 ERROR: while syncing Drafts [account ysten]
  While attempting to find UID for message with header X-OfflineIMAP, got wrong-sized matchinguids of ['SEARCH', 'search', 'error:', "can't", 'search', 'that', 'criteria']
 ERROR: ERROR in syncfolder for ysten folder Drafts: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/accounts.py", line 625, in syncfolder
    localfolder.syncmessagesto(remotefolder, statusfolder)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 1116, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 944, in __syncmessagesto_copy
    self.copymessageto(uid, dstfolder, statusfolder, register=0)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 844, in copymessageto
    new_uid = dstfolder.savemessage(uid, message, flags, rtime)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 692, in savemessage
    headervalue)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 397, in __savemessage_searchforheader
    (headername, str(matchinguids)))
ValueError: While attempting to find UID for message with header X-OfflineIMAP, got wrong-sized matchinguids of ['SEARCH', 'search', 'error:', "can't", 'search', 'that', 'criteria']

  While attempting to find UID for message with header X-OfflineIMAP, got wrong-sized matchinguids of ['SEARCH', 'search', 'error:', "can't", 'search', 'that', 'criteria']
Folder INBOX [acc: ysten]:
 Syncing INBOX: IMAP -> Maildir
 Copy message UID -2 (1/2) Local:INBOX -> Remote
```

- 
-

**Comment by nicolas33** [comment] 2017-04-05 07:54
Is this your own IMAP server? Can you check the logs of the server? What does `offlineimap --info` return?

**Comment by nicolas33** [comment] 2017-04-05 07:55
And `offlineimap -V`?

**Comment by csfreebird** [comment] 2017-04-05 08:19
We do not own IMAP server. 
```
offlineimap -V
offlineimap v7.0.14, imaplib2 v2.57 (bundled), Python v2.7.12+
```

**Comment by nicolas33** [comment] 2017-04-05 14:27
What does `offlineimap --info` return?

**Comment by csfreebird** [comment] 2017-04-05 14:31
```
$ offlineimap --info
OfflineIMAP 7.0.14
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
  imaplib2: 2.57 (bundled)
Remote repository 'Remote': type 'IMAP'
Host: imap.263.net Port: None SSL: False
Establishing connection to imap.263.net:143 (Remote)
Server supports ID extension.
Server welcome string: * OK [CAPABILITY IMAP4 IMAP4rev1 XLIST ID STARTTLS] 263Mail IMAP4Server ready
Server capabilities: ('IMAP4', 'IMAP4REV1', 'XLIST', 'ID')

Folderlist:
 Archive
 Deleted Messages
 Draft
 Drafts
 INBOX
 Junk
 Sent
 Sent Messages
 Trash

Local repository 'Local': type 'Maildir'
Folderlist:
 Archive
 Sent Messages
 Deleted Messages
 INBOX
 Drafts
 Junk
 Draft
 Sent
 Trash
```

**Comment by nicolas33** [comment] 2017-04-05 17:27
The `X-OfflineIMAP` trick is lesser and lesser used these times. However, your IMAP server does not support UIDPLUS.

On top of this, the IMAP server seems to not support SEARCH on this header. This would require more digging, though. I wonder offlineimap only raise the error when the requested header is not present.

**Comment by csfreebird** [comment] 2017-04-06 01:31
Because it stucks my mu4e for emacs. I have to write a python script to kill the offlineimap process if it lives over 1 minute.  Just a temporary way.

**Comment by nicolas33** [comment] 2017-04-06 07:04
I'll try a patch so that the process doesn't block. I won't have time to write it this week, though.

**Comment by nicolas33** [comment] 2017-04-07 18:34
With the above version offlineimap should continue the sync process while hitting this issue. This does not fix the root cause, though. Let me know if this works as expected, please.

**Comment by csfreebird** [comment] 2017-04-09 02:45
I tried your code, modify IMAP.py and rebuild the offlineimap. It sitll sutcks. Below is my console output:
```
$ offlineimap
OfflineIMAP 7.0.14
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync ysten:
 *** Processing account ysten
 Establishing connection to imap.263.net:143 (Remote)
Folder Archive [acc: ysten]:
 Syncing Archive: IMAP -> Maildir
Folder Deleted Messages [acc: ysten]:
 Syncing Deleted Messages: IMAP -> Maildir
Folder Draft [acc: ysten]:
 Syncing Draft: IMAP -> Maildir
Folder Drafts [acc: ysten]:
 Syncing Drafts: IMAP -> Maildir
 Copy message UID 1125 (1/5) Remote:Drafts -> Local
 Copy message UID 1126 (2/5) Remote:Drafts -> Local
 Copy message UID 1127 (3/5) Remote:Drafts -> Local
 Copy message UID 1128 (4/5) Remote:Drafts -> Local
 Copy message UID 1129 (5/5) Remote:Drafts -> Local
 Copy message UID -5 (1/5) Local:Drafts -> Remote
 ERROR: CWhile attempting to find UID for message with header X-OfflineIMAP, got wrong-sized matchinguids of ['SEARCH', 'search', 'error:', "can't", 'search', 'that', 'criteria']
 Copy message UID -4 (2/5) Local:Drafts -> Remote
 ERROR: CWhile attempting to find UID for message with header X-OfflineIMAP, got wrong-sized matchinguids of ['SEARCH', 'search', 'error:', "can't", 'search', 'that', 'criteria']
 Copy message UID -3 (3/5) Local:Drafts -> Remote
 ERROR: CWhile attempting to find UID for message with header X-OfflineIMAP, got wrong-sized matchinguids of ['SEARCH', 'search', 'error:', "can't", 'search', 'that', 'criteria']
 Copy message UID -2 (4/5) Local:Drafts -> Remote
 ERROR: CWhile attempting to find UID for message with header X-OfflineIMAP, got wrong-sized matchinguids of ['SEARCH', 'search', 'error:', "can't", 'search', 'that', 'criteria']
 Copy message UID -1 (5/5) Local:Drafts -> Remote
 ERROR: CWhile attempting to find UID for message with header X-OfflineIMAP, got wrong-sized matchinguids of ['SEARCH', 'search', 'error:', "can't", 'search', 'that', 'criteria']
Folder INBOX [acc: ysten]:
 Syncing INBOX: IMAP -> Maildir
 Copy message UID -2 (1/2) Local:INBOX -> Remote
```

I print CWhile instead While to make sure your code works in my machine.

**Comment by nicolas33** [comment] 2017-04-09 10:34
The patch works: offlineimap continue with the next email to download.

All the logs you provided are about the Drafts folder. Is there the same issue for other folders?

**Comment by csfreebird** [comment] 2017-04-11 05:20
still stuck, I have to use my python to kill it after one minute.

**Comment by nicolas33** [comment] 2017-04-11 06:31
> still stuck, I have to use my python to kill it after one minute.

Interesting. What do you mean by "I have to use my python"?
All the logs you provided are about the Drafts folder. Is there the same issue for other folders?

**Comment by csfreebird** [comment] 2017-04-17 05:27
I mean it stuck below instead of  "Local:Drafts -> Remote"

```
Folder INBOX [acc: ysten]:
 Syncing INBOX: IMAP -> Maildir
 Copy message UID -2 (1/2) Local:INBOX -> Remote
```
I have to use my python to kill the process.

**Comment by chris001** [comment] 2017-04-17 08:53
Why negative UID `-2` ??

**Comment by nicolas33** [comment] 2017-04-17 10:12
@csfreebird Please, provide more detailed log. 
@chris001 The logs are stripped too much.

**Comment by csfreebird** [comment] 2017-04-23 08:43
@nicolas33 please tell me how to provide detail log, I am new to offlineimap.

**Comment by nicolas33** [comment] 2017-04-23 10:47
`offlineimap -dALL` enable the debug logs. What I was saying is that the provided logs are shortened too much when pasted here. ,-)

**Comment by nicolas33** [comment] 2017-05-02 04:39
I realize I've never explained why the negative UID. This one is normal since offlineimap is uploading a mail. The output is mixed because of concurrency. ,-)

**Comment by nicolas33** [comment] 2017-05-19 06:42
You might like to folderfilter the folders to get the offending one.

**Comment by nicolas33** [comment] 2017-06-08 17:30
I'm closing because we got no feedbacks. We'll re-open on response.

**Closed by nicolas33** 2017-06-08 17:30 UTC
Labels: need contributor!, waiting submitter feedback
