### ISSUE TITLE
IDLE fetching empty messages

### ISSUE THREAD

**Issue by untitaker** [OfflineIMAP/offlineimap#162] opened 2015-01-29 20:12 UTC
OfflineIMAP sometimes fetches completely empty messages when new ones appear in the INBOX. I am not sure whether this happens because mutt is open.

I am using dovecot 2.0.15, the client is on Archlinux.

**Comment by nicolas33** [comment] 2015-02-12 14:51
It's hard to dig into without more context. Please, provide your offlineimap version and the configuration options you use, at least. Run `offlineimap --info`, too.

**Comment by untitaker** [comment] 2015-02-12 15:31
Sorry about that, it's usually not my style.

[My ``.offlineimaprc`` is available in a repo](https://github.com/untitaker/dotfiles/blob/master/home/.offlineimaprc), and I put the ``--info`` output in a [gist](https://gist.github.com/untitaker/ede7051017a2c5679f93) (which also includes its version, 6.5.5).

This only happens extremely rarely. It even might be that it completely stopped because of the recently added ``sockettimeout``, but I can't really say.

**Comment by nicolas33** [comment] 2015-02-12 15:52
Ok, so I'm closing. If the bug reappear, tell us if this happens for your "INBOX" since it's the only IDLE folder.

Thanks,

**Comment by untitaker** [comment] 2015-02-15 20:21
Argh, it happens again.

Yes, only for the IDLE folder.

**Comment by nicolas33** [comment] 2015-02-16 20:34
Try copying an offending mail somewhere else, remove it from the IDLE folder and redownload it with all debug options.

**Comment by untitaker** [comment] 2015-02-16 20:41
If I remove it from the IDLE folder, it will be removed from the serverside too. OfflineIMAP treats the empty message like a fully downloaded one.

**Comment by nicolas33** [comment] 2015-02-16 22:47
Of course, hence the `copying` before step.
Side note: talking by mail through the mailing list would be much easier. No subscribe required. ,-)

**Comment by a3nm** [comment] 2016-02-11 13:11
I also have the issue of offlineimap downloading empty messages. When I try to view them in mutt, these messages appear to consist of a single integer value. Some of these messages also seem to have flags.

**Comment by nicolas33** [comment] 2016-02-11 14:32
Are the empty messages empty on the server? Could you get those messages and provide samples?

**Comment by a3nm** [comment] 2016-02-11 14:38
It seems that the dummy messages never get sent to the server.

In the local maildir, these messages show up as follows in the "new" folder:

```
-rw------- 1 a3nm a3nm    1 Jan 18 12:28 1453116525_0.20909.mu,U=71401,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 18 20:00 1453143641_0.11288.mu,U=71433,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 19 15:09 1453212558_1.11288.mu,U=71511,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 19 15:14 1453212868_0.11288.mu,U=71519,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 20 11:15 1453284934_0.17624.mu,U=71587,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 22 14:52 1453470756_0.5164.mu,U=71773,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 23 15:07 1453558036_0.2850.mu,U=71871,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 24 22:27 1453670857_0.2850.mu,U=71935,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 24 22:47 1453672049_0.2850.mu,U=71938,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 25 15:49 1453733357_0.2850.mu,U=71990,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 26 20:00 1453834850_1.16493.mu,U=72152,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 26 22:35 1453844159_0.16493.mu,U=72176,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 27 00:02 1453849366_0.16493.mu,U=72214,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 27 11:45 1453891509_0.4201.mu,U=72275,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 27 11:51 1453891861_0.4201.mu,U=72277,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 27 13:36 1453898187_0.4201.mu,U=72305,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 27 22:17 1453929452_0.20651.mu,U=72418,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 28 12:08 1453979333_0.2632.mu,U=72470,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 28 14:05 1453986339_0.12638.mu,U=72497,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 28 16:48 1453996087_0.12638.mu,U=72533,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,
-rw------- 1 a3nm a3nm    1 Jan 28 20:38 1454009939_0.12638.mu,U=72570,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,
-rw------- 1 a3nm a3nm    1 Jan 29 15:11 1454076660_0.25893.mu,U=72700,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Jan 29 16:36 1454081787_0.5809.mu,U=72727,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,
-rw------- 1 a3nm a3nm    1 Jan 30 09:03 1454141018_0.16870.mu,U=72791,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Feb  2 17:57 1454432239_0.16870.mu,U=72910,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Feb  3 13:13 1454501612_0.16870.mu,U=72951,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,
-rw------- 1 a3nm a3nm    1 Feb  7 12:34 1454844855_0.28670.mu,U=73099,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Feb  9 00:08 1454972898_0.31506.mu,U=73217,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Feb  9 00:43 1454975039_0.31506.mu,U=73241,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Feb  9 12:10 1455016212_0.20282.mu,U=73275,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,
-rw------- 1 a3nm a3nm    1 Feb  9 18:23 1455038625_0.20282.mu,U=73313,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Feb  9 18:23 1455038627_0.20282.mu,U=73314,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Feb  9 20:10 1455045050_0.20282.mu,U=73323,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Feb 10 00:05 1455059111_0.20282.mu,U=73344,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T
-rw------- 1 a3nm a3nm    1 Feb 10 00:57 1455062256_0.20282.mu,U=73357,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,T

```

For each of these files, the single byte that they contain is a single digit with no trailing newline. Here they are:

```
1
4
4
5
4
1
0
7
7
2
5
0
0
1
1
1
2
3
2
3
1
5
5
6
7
7
9
9
0
1
1
1
1
1
7
```

**Comment by nicolas33** [comment] 2016-02-11 16:06
They are not sent if they already exist on remote. How the mails with those UID look like?

**Comment by a3nm** [comment] 2016-02-13 00:38
I think this is described by the second part of my previous comment? Is there any more information that I can get out of them?

**Comment by nicolas33** [comment] 2016-02-13 08:27
@a3nm AFAIU, OfflineIMAP locally creates mails with no or unexpected data. I'd like to know what those mails are on the remote side. Are they the exact same? This would need to connect to the webmail or another IMAP client to check.

**Comment by a3nm** [comment] 2016-02-13 09:59
Sorry, now I understand. These mails do not exist at all on the remote side, they only exist on the local side. (Checked by connecting with a different IMAP client.)

**Comment by nicolas33** [comment] 2016-02-13 11:12
That's not exactly what the list of filenames suggest since they have a UID. I guess they exist with the real content.

Anyway, I found this in the mailing list:
```
Subject: Bug (& patch): Corrupted messages containing a single byte
From: Austin Clements <hidden>
Date: Thu, 06 Dec 2012 23:32:37 -0500
Message-ID: <878v9apjmi.fsf@awakening.csail.mit.edu>
```
The patch might never got in. Needs check.

**Comment by nicolas33** [comment] 2016-07-28 05:38
Patch applied.

**Closed by nicolas33** 2016-07-28 05:38 UTC
Labels: bug, IDLE, need contributor!

**Comment by untitaker** [comment] 2016-07-28 10:26
Thanks, will reenable IDLE to test!

**Comment by untitaker** [comment] 2016-07-28 10:26
Do you have an ETA for when this will be released as stable version?

On 28 July 2016 07:38:05 CEST, Nicolas Sebrecht <notifications@github.com> wrote:
>Closed #162.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OfflineIMAP/offlineimap/issues/162#event-737387080

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nicolas33** [comment] 2016-07-28 15:56
I don't have ETA. I'd like it with all the bugs/regressions fixed.

Yes, test please. Thanks!

**Comment by untitaker** [comment] 2016-07-28 20:23
> I don't have ETA. I'd like it with all the bugs/regressions fixed.

In this particular case, however, I can't test within such a limited timespan
since the problem only appears sporadically.

**Comment by nicolas33** [comment] 2016-07-29 00:26
Ok. Not that bad. At least, the patch does not seem to harm. So, I'll consider the fix right unless someone reports here it's not.

Thanks!
