### ISSUE TITLE
Error append command

### ISSUE THREAD

**Issue by rogorido** [OfflineIMAP/offlineimap#284] opened 2015-12-20 21:44 UTC
With the last 6.6.0 I'm getting the following error:

ERROR: Saving msg (<20151220212257.GA25793@suno.homestation>) folder 'Sent', repo 'Remote-erfurt'failed (error). Server responded: APPEND command error: BAD ['Missing required argument to Append command']. Data: OJCH24 APPEND Sent (\Seen) "20-Dec-2015 22:22:57 +0100" ~{1106}

I do not know whether this is related to https://github.com/OfflineIMAP/offlineimap/issues/172

The master version gives also the same error. How could I debug this error?

**Comment by nicolas33** [comment] 2015-12-20 22:06
Try with `-d imap`.
You could check if it works with previous stable version.

**Comment by rogorido** [comment] 2015-12-20 22:18
thanks for your answer.  Yes, it worked. I never saw this error. I'm using archlinux, and it is not so easy to come back to a previous version... But, it worked.

How can I direct the output of -d imap to a file? The usual > file.txt is not working.

**Comment by nicolas33** [comment] 2015-12-20 23:11
Look at `-- help`.

**Comment by rogorido** [comment] 2015-12-21 09:09
Thanks. The main log entries can be seen here: http://pastie.org/10644898

The whole log file is too big. I can make it avalaible to you privately if it is necessary.

**Comment by nicolas33** [comment] 2015-12-21 13:56
Do you still have the problem? The logs looks good.

**Comment by rogorido** [comment] 2015-12-21 14:03
Thanks for your answer. Yes, I have. Are there other possible tests I could make?

**Comment by nicolas33** [comment] 2015-12-21 15:23
The best is to start from the logs. The current one does not provide the correct excerpt or there was no issue during the run.
Make sure that the filename is a new filename once edited. Oterwhise, it won't propagate any change since it's the expected behaviour.

**Comment by nicolas33** [comment] 2015-12-21 15:24
Oh, another thing you could try is to git bisect the issue: http://offlineimap.org/doc/git-bisect.html

**Comment by rogorido** [comment] 2015-12-21 16:01
Thanks. I managed to downgrade to version 6.5.7 and the problem disappears. It is obviously some changes between these versions. I will investigate...

**Comment by mardukbp** [comment] 2015-12-24 21:11
I started having exactly the same problem (with iCloud) after Arch upgraded to version 6.6. The culprit is line 1388 in `offlineimap/imaplib2.py`. More precisely, the tilde causes the error. I learned this after issuing `offlineimap -d -q` and googling for "Missing required argument to Append command". [This](http://squirrelmail.org/wiki/ComposeErrorOnSend) gave me the hint. Maybe that character has to be escaped.

**Comment by nicolas33** [comment] 2015-12-26 13:30
Sent a mail to upstream.

**Comment by nicolas33** [comment] 2015-12-28 00:46
Fixed in v6.6.1.

**Closed by nicolas33** 2015-12-28 00:46 UTC
Labels: bug, need contributor!, waiting for upstream

**Comment by rogorido** [comment] 2015-12-28 13:35
Thanks!
